### ISSUE TITLE
Add yourself to the participants list

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#1]
Star this repo and everyother repo in opencode for the pull request to be merged :wink:
Go through the readme for guidlines

Staring is to ensure that you saw all the projects in opencode.

**Comment by aadixiiita** [comment]
I would like to work on this .

**Comment by guptaaman70659** [comment]
it is good platform to convert effort in succsess

**Comment by anshumanv** [comment]
Completed in #135

**Comment by anandwana001** [comment]
@aswinzz some of the participants images are not visible on website. If this issue can act as a separate issue please do assign to me, would like to do this.

**Comment by ashutosh97** [comment]
Please review https://github.com/opencode18/OpenCode-Collaborative/pull/452
