### ISSUE TITLE
Add card for projects 

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#102]
Add card in same way as persons name .
and a json should be created for projects.
take projects list.
Comment on issue #31 along witht the screenshot to get your marks verified. :smile:

**Comment by aayushjoglekar** [comment]
I can do this

**Comment by Tlazypanda** [comment]
i would be interested

**Comment by gauthamzz** [comment]
only one issue per person at a time.
@Tlazypanda assigned to you

**Comment by aswanthkoleri** [comment]
@Tlazypanda  whats the status ?

**Comment by pradeepgangwar** [comment]
#187 related to this got merged.

**Comment by mubaris** [comment]
@aayushjoglekar New Projects have added. [Check This](https://opencode18.github.io/projects)

Add new projects and fix mentor error (Right Now "OpenNews" is mentored by Team OpenCode instead of Aswanth and "yes" is mentored by Aswanth instead of Mubaris NK)
