### ISSUE TITLE
Make the flipped card automatically reset after sometime

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#115]
when we click on the card it stays flipped until we click it again, so make it reset after say 3 to 4 sec.

**Comment by falconis** [comment]
Can I take this?

**Comment by atisayajain** [comment]
I would like to work on this.

**Comment by aswinzz** [comment]
@falconis you have been assigned

**Comment by aswinzz** [comment]
@falconis  updates?

**Comment by falconis** [comment]
I'll complete today after my lab. @aswinzz

**Comment by falconis** [comment]
Do I need to use javascript for this?
