### ISSUE TITLE
Remove bottom scrollbar

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#126]
there is scroll bar for moving left/right which is useless.
more precisely, there is some content which has extending width, fix that.
A PR with horizontal scroll disabled will not be merged.

**Comment by dojutsu-user** [comment]
i will like to do it. please assign it to me

**Comment by permanent-bnsl** [comment]
Can I do this please.?

**Comment by aswinzz** [comment]
@dojutsu-user is assigned

**Comment by dojutsu-user** [comment]
@aswinzz done
i have referenced this issue under #130

**Comment by aswinzz** [comment]
Fix it once more @dojutsu-user
