### ISSUE TITLE
fix mobile view for grid

### ISSUE THREAD

**Issue by Anupam-dagar** [opencode18/OpenCode-Collaborative#127]
grid is not centered in mobile view.
![screenshot from 2018-01-11 13-31-53](https://user-images.githubusercontent.com/21174572/34814501-e078ab38-f6d3-11e7-8092-e0d79e270a21.png)
Comment on issue #31 along witht the screenshot to get your marks verified. :smile:

**Comment by Ace-Bansal** [comment]
can i do it?

**Comment by aswinzz** [comment]
@Ace-Bansal  you are assigned!

**Comment by Esha23** [comment]
I want to resolve the issue. Can I?

**Comment by abhishhh1** [comment]
May I work on this issue?

**Comment by gauthamzz** [comment]
Fix this issue fast

**Comment by aswinzz** [comment]
@Esha23  you can work on this
