### ISSUE TITLE
star this repository

### ISSUE THREAD

**Issue by Anupam-dagar** [opencode18/OpenCode-Collaborative#128]
comment your screenshot here to get points rewarded.

**Comment by Ace-Bansal** [comment]
![screenshot 18 _li](https://user-images.githubusercontent.com/34866483/34815816-ddc145a8-f6d8-11e7-85d1-20ec4f07017b.jpg)

**Comment by permanent-bnsl** [comment]
![screenshot](https://user-images.githubusercontent.com/35285444/34815938-4ac0ba3a-f6d9-11e7-80ed-f03e801c10ea.png)

**Comment by 16priyesh** [comment]
![16priyesh](https://user-images.githubusercontent.com/28901008/34816040-9c925daa-f6d9-11e7-8706-3bdd5fba5f5c.png)

**Comment by RudRA-8** [comment]
![image](https://user-images.githubusercontent.com/33032175/34816382-c18016ba-f6da-11e7-93a4-6a6ee1b54318.png)

**Comment by RudRA-8** [comment]
![image](https://user-images.githubusercontent.com/33032175/34816405-d42f5fbe-f6da-11e7-981c-9ae4562f05a9.png)

**Comment by aadixiiita** [comment]
![screenshot_20180111-143408](https://user-images.githubusercontent.com/34688457/34816968-915745c4-f6dc-11e7-883a-bbfb71ad035f.png)

**Comment by abhishhh1** [comment]
![screenshot 2](https://user-images.githubusercontent.com/31480124/34817041-c51c1f06-f6dc-11e7-8ab5-a4d818a9980d.png)

**Comment by amriteshbhaskar** [comment]
![screenshotgit](https://user-images.githubusercontent.com/34058250/34817185-3b3d24aa-f6dd-11e7-9462-1084c00ef1d0.png)

**Comment by ProBeta1** [comment]
![screenshot-2018-1-11 probeta1 abhinav kumar srivastava](https://user-images.githubusercontent.com/33081197/34818494-f093e570-f6e0-11e7-91f9-571a1be461fd.png)

**Comment by anshumanv** [comment]
How do I know how much points I have?
![image](https://user-images.githubusercontent.com/21009455/34820259-0a2f4cc2-f6e6-11e7-9751-7487ff8c9898.png)

**Comment by dojutsu-user** [comment]
![capture](https://user-images.githubusercontent.com/29149191/34820330-2e83e088-f6e6-11e7-85f1-f4ffe9c02ed9.PNG)

**Comment by surasnayak** [comment]
Done!
![untitled2](https://user-images.githubusercontent.com/21239888/34823239-b185fd50-f6ef-11e7-944a-9dffeafeca01.png)

**Comment by helios1101** [comment]
![capture7](https://user-images.githubusercontent.com/26597930/34824566-03c17428-f6f5-11e7-9a34-8b2934389df5.JPG)

**Comment by prathamprakash29** [comment]
![image](https://user-images.githubusercontent.com/30841366/34826243-d3600608-f6fb-11e7-9844-21c8bc8ab8f5.png)

**Comment by Tlazypanda** [comment]
![screenshot_2018-01-11-18-27-57](https://user-images.githubusercontent.com/33183263/34826600-3e0a1fa6-f6fd-11e7-8ba1-dc7ddfe26b1d.png)

**Comment by Anjali2901** [comment]
![screenshot 43](https://user-images.githubusercontent.com/25278194/34827812-6a24d8b6-f701-11e7-89ef-99e4764e8992.png)

**Comment by Re42** [comment]
![image](https://user-images.githubusercontent.com/33805964/34829016-6004b33e-f705-11e7-989e-79db94180931.png)

**Comment by ashraysinha6069** [comment]
![screenshot - 1_11_2018 7_29_04 pm](https://user-images.githubusercontent.com/34709632/34829242-0eab7008-f706-11e7-93ea-1e118fd0ac31.png)

**Comment by namantw** [comment]
![image](https://user-images.githubusercontent.com/31323328/34829590-36f28852-f707-11e7-9a3d-fc2b704af3a2.png)

**Comment by Esha23** [comment]
![screenshot-2018-1-11 esha23](https://user-images.githubusercontent.com/35305010/34831655-8998b76a-f70d-11e7-8a5a-866db6583268.png)

**Comment by NeroIS** [comment]
![screenshot 2](https://user-images.githubusercontent.com/31174719/34831943-7dc7baa2-f70e-11e7-89b4-0b5dc565b890.png)

**Comment by DEVILCODER-SB99** [comment]
![screenshot 2](https://user-images.githubusercontent.com/33373098/34832172-24a0139c-f70f-11e7-85b7-bd61b50bd9be.png)

**Comment by Panda2498** [comment]
![star collaborate](https://user-images.githubusercontent.com/34282889/34833793-43ae77c2-f716-11e7-9aa0-2d87f5d4c4c9.PNG)

**Comment by masterchef2209** [comment]
![1](https://user-images.githubusercontent.com/27916352/34833833-63497104-f716-11e7-887d-dc9a029cdb5e.jpg)

**Comment by Divy123** [comment]
![screenshot from 2018-01-11 21-57-38](https://user-images.githubusercontent.com/31225007/34835324-7eade142-f71a-11e7-8422-9e48caa3783c.png)

**Comment by strikertanmay** [comment]
![screenshot from 2018-01-11 22-02-26](https://user-images.githubusercontent.com/32292953/34836171-0cda7d48-f71d-11e7-8375-5bec2e0e4874.png)

**Comment by arpitmisraw** [comment]
![screenshot from 2018-01-11 23-01-41](https://user-images.githubusercontent.com/32339738/34838283-8aaca402-f723-11e7-87ca-2744f0ad953d.png)

**Comment by Anubhav2000** [comment]
![capture](https://user-images.githubusercontent.com/33462670/34839937-61c2568a-f729-11e7-86ca-2d73e183133a.PNG)

**Comment by adiagg2000** [comment]
![screenshot 34](https://user-images.githubusercontent.com/33027339/34842539-d259f882-f731-11e7-98fa-ad7e71fc7985.png)

**Comment by aayushjoglekar** [comment]
![image](https://user-images.githubusercontent.com/28949397/34844392-579e9430-f737-11e7-9353-10d10ee4da89.png)

**Comment by gau1rav** [comment]
![starred2](https://user-images.githubusercontent.com/34263673/34847160-7218e258-f740-11e7-9fbd-7e0320c2bcda.png)

**Comment by blaze17280** [comment]
![blaze](https://user-images.githubusercontent.com/35065475/34847258-8f5436d6-f6cf-11e7-8ea6-28150a8c068b.png)

**Comment by cuz789** [comment]
![2018-01-12](https://user-images.githubusercontent.com/35086901/34847288-d76ff358-f740-11e7-8346-c3bb364e9189.png)

**Comment by vvvinamer** [comment]
![screenshot 39](https://user-images.githubusercontent.com/35339278/34869111-eca67484-f7ab-11e7-8068-71cd72e3eea0.png)

**Comment by maverick0004** [comment]
![screenshot from 2018-01-12 15-20-49](https://user-images.githubusercontent.com/33194760/34869241-4adcc616-f7ac-11e7-8ec8-deee5789a1f9.png)

**Comment by Eunoia1729** [comment]
![screenshot from 2018-01-12 20-00-11](https://user-images.githubusercontent.com/33084435/34879502-823d7d9a-f7d3-11e7-82e4-22d847d59a05.png)

**Comment by ShiningSaurabh** [comment]
![capture](https://user-images.githubusercontent.com/34839782/34891255-ed4371e0-f7fa-11e7-97d5-bcb53b03ec60.PNG)

**Comment by atisayajain** [comment]
![capture](https://user-images.githubusercontent.com/19758073/34904270-7c8a2e94-f868-11e7-92e6-b2c12c2a2ea1.PNG)

**Comment by shivhek25** [comment]
![screenshot](https://user-images.githubusercontent.com/24766191/34904375-8e6a6230-f86a-11e7-8343-2ab90bfc2ad8.png)

**Comment by shantam0810** [comment]
![opcode](https://user-images.githubusercontent.com/35340673/34904821-810cfbbc-f873-11e7-8f34-7d6efc96965f.PNG)

**Comment by MaanasVohra** [comment]
![screen shot 2018-01-13 at 7 05 15 pm](https://user-images.githubusercontent.com/25277647/34906435-d34b4062-f893-11e7-8973-d79f549a63bf.png)

**Comment by priyanka-choubey** [comment]
![screenshot 6](https://user-images.githubusercontent.com/33806116/34913404-940a4148-f922-11e7-91e8-b7440be84938.png)
