### ISSUE TITLE
Add a field for college in contestants.json and display it

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#133]
add field for college in contestants.json and display college name in the about section in the card. 
update the steps in the readme too.

**Comment by falconis** [comment]
Can I take this

**Comment by aayushjoglekar** [comment]
I wanna do this.

**Comment by aswinzz** [comment]
@falconis  complete the work you are assigned.
@aayushjoglekar  you can take up this issue

**Comment by aayushjoglekar** [comment]
I am making up the college key in json which the contestants will have to fill. Okay?
