### ISSUE TITLE
Suggest new issues

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#136]
Suggest ideas for improvement of the site at comments, when suggesting be breif.
After that we will make issues , if we find it good. For each issue we make you get 20 points.
Issues will be made by the mentors and anyone can take up those issues
we will be deleting the comments which are not good!

**Comment by anshumanv** [comment]
Adding a `back to top` floating button on bottom-right could be nice to get back to the top.

**Comment by anshumanv** [comment]
Presently about section is plain text, it can be greatly improved with a proper bg and logo.

**Comment by hacker1x1x1** [comment]
we can add a custom scrollbar having scrollbar track of white background(same as that of the webpage) and the color of the bar can be the same as background color of frontpage!

**Comment by hacker1x1x1** [comment]
Also, the footer can have a light shadow background! just to look better

**Comment by AK-007** [comment]
We can add a Leaderboard for tracking points for OpenCode'18.

**Comment by falconis** [comment]
A night mode would be good.

**Comment by aadixiiita** [comment]
We can add links to Opencode'18 , Opennews , Medium.com opencode blogs sites ...

**Comment by aswinzz** [comment]
@aadixiiita  that issue is already there.
@AK-007  we will be adding it in coming days. 
@hacker1x1x1 changing the footer background cant be awarded any marks , if you are interested you can do that.

**Comment by Panda2498** [comment]
Add a tab of Opencode news or new added projects on the right side of mentors and participants tabs

**Comment by gauthamzz** [comment]
@Panda2498 that will be done once the cards are made for them.

**Comment by Anubhav2000** [comment]
A timer for displaying the time left for the event to end can be displayed at the top left corner of the page!

**Comment by aayushjoglekar** [comment]
Reduce the width of custom scrollbar added.
Make scrollbar background transparent and add gradient to scrollbar.

**Comment by Divy123** [comment]
Schedule of Event should be updated

**Comment by aayushjoglekar** [comment]
Seperate folder to be made for JSON files and update their links should be updated in their respective js files.

**Comment by aayushjoglekar** [comment]
Make the footer responsive.

**Comment by aayushjoglekar** [comment]
@aswinzz 
Add more projects in issues section and add a link for issues section in navbar.

**Comment by aayushjoglekar** [comment]
Fix mobile view of issues section.
![screenshot_20180113-022512](https://user-images.githubusercontent.com/28949397/34894850-03dd6916-f809-11e7-8920-8bd771534128.png)

**Comment by aayushjoglekar** [comment]
Make each section's heading the same as issues section.

![screenshot_20180113-022750 01](https://user-images.githubusercontent.com/28949397/34894933-6d84e506-f809-11e7-8272-8f309a8ba34a.png)

**Comment by gauthamzz** [comment]
Yeah last three ideas seem neat, add them someone. On mobile 😅

**Comment by MaanasVohra** [comment]
Issues for all the projects aren't there under the projects section.

**Comment by aadixiiita** [comment]
We can change CSS/Looks/Colour of Top Nav bar and The animation behind fav icon , As it is not so attractive in Grey ...

**Comment by Panda2498** [comment]
Stars and forks, don't display the number of stars and forks yet! Link it to the github page to view it.

**Comment by Panda2498** [comment]
Add issues of all projects, as of now issues of only 2 projects are there.

**Comment by surasnayak** [comment]
A image file named saurabh.png is uploaded in the main repository instead of inside contestants folder.
Move it to the Contestants folder.
I would like to do.

**Comment by surasnayak** [comment]
Issues from only two projects are being shown add all of them

**Comment by surasnayak** [comment]
In the footer the social icons can be made more elegant by enlarging slightly and adding some animation while hovering over it.

**Comment by surasnayak** [comment]
Auto turn of cards when we hover over it feature would be really good to add.

**Comment by surasnayak** [comment]
facebook link which has been added is flickering when we hover away from downward it.

**Comment by falconis** [comment]
Back side of cards show parts from the front side in mobile.
![Uploading Screenshot (Jan 17, 2018 5_46_27 PM).png…]()

**Comment by falconis** [comment]
Back side of cards show parts of the front side in mobile:
![screenshot jan 17 2018 5_46_27 pm](https://user-images.githubusercontent.com/30634978/35042894-5fe1fcb8-fbb0-11e7-9b12-5c9154f41084.png)

**Comment by nityanandagohain** [comment]
![screenshot from 2018-01-17 19-34-20](https://user-images.githubusercontent.com/26831659/35046655-a38da8d8-fbbd-11e7-87ad-e4f5fbe60d48.png)
It should aligned to the centre

**Comment by swaager** [comment]
Website made by the participants can be added in the backside of the participants card.

**Comment by arpitmisraw** [comment]
The trailer still won't stop playing after it's closed. Also some weird youtube link appears on the top right when the trailer is played.

**Comment by shivhek25** [comment]
After a card is clicked on, it shows the information and the links for a second (i.e. while flipping) and then shows the original image in the card and the text in a mirrored fashion. 
Here, look at the card next to that of the mentor "Harshit jain".

![screen shot 2018-01-24 at 11 56 04 pm](https://user-images.githubusercontent.com/24766191/35349870-2bd052f0-0162-11e8-974b-342534e46818.png)

**Comment by Re42** [comment]
![screenshot_20180124-154521](https://user-images.githubusercontent.com/33805964/35350565-5318708e-0164-11e8-9f03-e4352c574e25.jpg)

Alignment of fb on mobile

**Comment by Re42** [comment]
![screenshot_20180124-154513](https://user-images.githubusercontent.com/33805964/35350884-49c2bf0c-0165-11e8-96b9-83efe1dd9768.jpg)
alignment of fb tab on mobile previous comment can also be example of this
