### ISSUE TITLE
Irrelevant horizontal scroll bar

### ISSUE THREAD

**Issue by anshumanv** [opencode18/OpenCode-Collaborative#137]
I'm willing to fix this, can this be considered a task?

![image](https://user-images.githubusercontent.com/21009455/34821366-78a6de10-f6e9-11e7-8d6e-d7f1c85a6002.png)

**Comment by pradeepgangwar** [comment]
@anshumanv yeah do it.

**Comment by aswinzz** [comment]
@anshumanv  if you find any issues comment it in the issue #136  and get it approved before making a new one.
btw this issue was made a day back and solved by @dojutsu-user before but it came back so it will be assigned to him itself.

**Comment by anshumanv** [comment]
@aswinzz Aight, cool. :+1:
