### ISSUE TITLE
like opencode fb page

### ISSUE THREAD

**Issue by Anupam-dagar** [opencode18/OpenCode-Collaborative#138]
https://www.facebook.com/opencodeiiita/
Comment you screenshots

**Comment by anshumanv** [comment]
Done, how do I know how many points I've racked up?

![image](https://user-images.githubusercontent.com/21009455/34822219-2436b6e0-f6ec-11e7-8ce7-84d1b6434f2b.png)

**Comment by Anupam-dagar** [comment]
hi @anshumanv 
leaderboard will be added after somedays, all the pull request merged are the proof for your points.

**Comment by surasnayak** [comment]
Done
![untitled](https://user-images.githubusercontent.com/21239888/34823025-f3d06d90-f6ee-11e7-88a1-efd04e4a8ac3.png)

**Comment by dojutsu-user** [comment]
![capture](https://user-images.githubusercontent.com/29149191/34823129-53fe5420-f6ef-11e7-9397-244723fa00f6.PNG)

**Comment by helios1101** [comment]
![Uploading Capture5.JPG…]()

**Comment by helios1101** [comment]
![capture5](https://user-images.githubusercontent.com/26597930/34824211-920ff67a-f6f3-11e7-81d7-9147f309f39c.JPG)

**Comment by SachinkumarIIITA** [comment]
![capture](https://user-images.githubusercontent.com/30855690/34824626-521c857c-f6f5-11e7-90b1-6450d416eac8.JPG)

**Comment by sud0lancer** [comment]
![image](https://user-images.githubusercontent.com/26188360/34824888-57d04a16-f6f6-11e7-9228-8ffe56145eb1.png)

**Comment by prathamprakash29** [comment]
![image](https://user-images.githubusercontent.com/30841366/34826136-6ad8a464-f6fb-11e7-862f-1100801e7da7.png)

**Comment by Tlazypanda** [comment]
![screenshot_2018-01-11-18-15-51](https://user-images.githubusercontent.com/33183263/34826294-05658ab0-f6fc-11e7-9262-f283736f9cea.png)

**Comment by hacker1x1x1** [comment]
![image](https://user-images.githubusercontent.com/34509429/34826349-0c7f4adc-f68b-11e7-8ef6-ffd97d24038e.png)

**Comment by Anjali2901** [comment]
![screenshot 45](https://user-images.githubusercontent.com/25278194/34827961-e291045a-f701-11e7-8f83-97d55d40f3be.png)

**Comment by AK-007** [comment]
![screenshot 52](https://user-images.githubusercontent.com/26346816/34828266-027af2ca-f703-11e7-87d4-b41abb334b45.png)

**Comment by GOVINDDIXIT** [comment]
![capture](https://user-images.githubusercontent.com/32304546/34828332-3f7a3064-f703-11e7-8596-d6ed4f539128.PNG)

**Comment by Re42** [comment]
![image](https://user-images.githubusercontent.com/33805964/34828765-939c6968-f704-11e7-9b92-f9525b9484df.png)

**Comment by ashraysinha6069** [comment]
![screenshot - 1_11_2018 7_25_26 pm](https://user-images.githubusercontent.com/34709632/34829004-573a91e2-f705-11e7-988d-ea88d7750a67.png)

**Comment by abhishhh1** [comment]
![screenshot 3](https://user-images.githubusercontent.com/31480124/34829116-aa375cf4-f705-11e7-841b-ae2a7e51f641.png)
I liked the page and given 5 stars in ratings too.

**Comment by namantw** [comment]
![image](https://user-images.githubusercontent.com/31323328/34829502-ea9292b8-f706-11e7-9872-243c2854d7ce.png)

**Comment by Ace-Bansal** [comment]
![screenshot 20](https://user-images.githubusercontent.com/34866483/34830462-eaa029c0-f709-11e7-88b9-b11be2d9cf60.png)

**Comment by swaager** [comment]
![openc](https://user-images.githubusercontent.com/29673845/34830605-6a6c7a5a-f70a-11e7-8db7-3eb64cf2bbe9.png)

**Comment by Anubhav2000** [comment]
![capture](https://user-images.githubusercontent.com/33462670/34830714-bdf2dfca-f70a-11e7-8378-08fe9f738c28.PNG)
Done!!

**Comment by Panda2498** [comment]
![opencode](https://user-images.githubusercontent.com/34282889/34831233-5b05487e-f70c-11e7-8013-c5e1d29bbd68.jpg)

**Comment by Esha23** [comment]
![screenshot-2018-1-11 opencode - home](https://user-images.githubusercontent.com/35305010/34831375-cb1768d6-f70c-11e7-8bb5-5c2f25b926e1.png)

**Comment by aayushjoglekar** [comment]
![image](https://user-images.githubusercontent.com/28949397/34831703-b12b50a8-f70d-11e7-98d6-f6cdbde5d3a2.png)

**Comment by DEVILCODER-SB99** [comment]
![screenshot 1](https://user-images.githubusercontent.com/33373098/34832068-d8fe3ba8-f70e-11e7-9c6a-a25e34e180ad.png)

**Comment by muskan6769** [comment]
![screenshot from 2018-01-11 20-39-13](https://user-images.githubusercontent.com/34505804/34832314-92212bc2-f70f-11e7-8de5-c5731eca376b.png)

**Comment by arpitmisraw** [comment]
![screenshot_2018-01-11-21-16-10-256_com facebook katana](https://user-images.githubusercontent.com/32339738/34833226-f10b4082-f714-11e7-9548-f1c48ff3ae06.png)

**Comment by KomalBhadani27** [comment]
![screenshot 50](https://user-images.githubusercontent.com/33183901/34833259-0777ece4-f715-11e7-9b5a-17cc10f35bc8.png)

**Comment by ananya-agrawal** [comment]
![op](https://user-images.githubusercontent.com/33188930/34835682-89f4b642-f71b-11e7-9a90-c924184c685e.png)

**Comment by strikertanmay** [comment]
![screenshot from 2018-01-11 22-07-27](https://user-images.githubusercontent.com/32292953/34835928-59229bbe-f71c-11e7-8fe4-42debe811207.png)

**Comment by adiagg2000** [comment]
![screenshot 33](https://user-images.githubusercontent.com/33027339/34842460-8fdb619e-f731-11e7-9fee-6da69485891c.png)

**Comment by SnigdhaDobhal** [comment]
![2018-01-11](https://user-images.githubusercontent.com/35201631/34839598-22790222-f728-11e7-9228-63931193c3a8.png)

**Comment by cuz789** [comment]
![2018-01-12 1](https://user-images.githubusercontent.com/35086901/34849162-7168e5a4-f747-11e7-93c6-d28531eabe2b.png)

**Comment by marshallKR7** [comment]
![screenshot-2018-1-12 1 opencode - home](https://user-images.githubusercontent.com/28799332/34863832-70d71142-f797-11e7-9f92-8f0d7fd95c25.png)

**Comment by vvvinamer** [comment]
![screenshot 37](https://user-images.githubusercontent.com/35339278/34869016-a05c3154-f7ab-11e7-81e1-48055ab2d45f.png)

**Comment by maverick0004** [comment]
![screenshot from 2018-01-12 15-22-46](https://user-images.githubusercontent.com/33194760/34869325-904e07b4-f7ac-11e7-84e1-1bfc5dc060b0.png)

**Comment by im-adi** [comment]
![screenshot](https://user-images.githubusercontent.com/33853663/34871329-43138ff8-f7b3-11e7-90df-9c668cc6b939.png)

**Comment by techac** [comment]
![screenshot](https://user-images.githubusercontent.com/33215722/34877472-334dbe5e-f7cc-11e7-9290-4970b6ded6ad.png)

**Comment by kamalchaubey1** [comment]
![screenshot from 2018-01-12 19-24-27](https://user-images.githubusercontent.com/25115489/34877985-5a5f5e4c-f7ce-11e7-8ad4-4f6f1f187d43.png)
DONE!

**Comment by Eunoia1729** [comment]
![askme](https://user-images.githubusercontent.com/33084435/34879829-8acc118c-f7d4-11e7-9d72-9a1c5785ecd1.png)

**Comment by pranjalg2308** [comment]
![like](https://user-images.githubusercontent.com/35169520/34888035-9ed9d8a2-f7ee-11e7-8be1-9e7dcd238733.PNG)

**Comment by RohanShekhawat** [comment]
![capture](https://user-images.githubusercontent.com/34987773/34888101-e1a37f1c-f7ee-11e7-85d8-8e969ab164cc.PNG)

**Comment by atisayajain** [comment]
![capture](https://user-images.githubusercontent.com/19758073/34904244-140385b4-f868-11e7-93a1-7ad9d8b295ec.PNG)

**Comment by MaanasVohra** [comment]
![screen shot 2018-01-13 at 7 00 36 pm](https://user-images.githubusercontent.com/25277647/34906413-5674e3d6-f893-11e7-947c-4e1ac8c3834e.png)

**Comment by brain-sick** [comment]
![screenshot_2018-01-14-02-24-01-961_com android chrome](https://user-images.githubusercontent.com/34164978/34910021-f9e70168-f8d2-11e7-8e8c-d880d5d84bfa.png)

**Comment by anandwana001** [comment]
![screenshot_2018-01-14-05-00-41-525_com facebook katana](https://user-images.githubusercontent.com/25057618/34911067-e7542390-f8e7-11e7-8b0d-19353d63adeb.png)

**Comment by kgauravk** [comment]
![screenshot 2018-01-15 00 15 30](https://user-images.githubusercontent.com/34207555/34919433-f30467c0-f989-11e7-9c9f-d32c08200a36.png)

**Comment by falconis** [comment]
![like](https://user-images.githubusercontent.com/30634978/36042983-c7f518da-0df3-11e8-8b2f-d584b34c403d.png)
