### ISSUE TITLE
Add custom scroll bar

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#158]
add a custom scrollbar overriding the standard scroll bar

Issue suggestions by - @hacker1x1x1

**Comment by aadixiiita** [comment]
I would like to work on it ..

**Comment by aswinzz** [comment]
yeah

**Comment by hacker1x1x1** [comment]
Adii has some other issue
Let me work on this

**Comment by aayushjoglekar** [comment]
I would like to work on this

**Comment by techac** [comment]
I would like to work on this
