### ISSUE TITLE
Add timer for coutdown till the event is over.

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#160]
Be minimal

**Comment by hacker1x1x1** [comment]
i would like tyo work on this

**Comment by Panda2498** [comment]
May I work on this?

**Comment by AK-007** [comment]
I would like to work on this

**Comment by gauthamzz** [comment]
assigned to @hacker1x1x1

**Comment by hacker1x1x1** [comment]
live link for updated custom scroll bar: https://hacker1x1x1.github.io/OpenCode-Collaborative/
