### ISSUE TITLE
Add watch trailer on nav bar and pop up for youtube video

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#163]

**Comment by arpitmisraw** [comment]
I would like to work on this.

**Comment by gauthamzz** [comment]
assigned to you @arpitmisraw

**Comment by aayushjoglekar** [comment]
I would like to work on this.

**Comment by arpitmisraw** [comment]
@gauthamzz  I can't seem to find the link for the youtube video. Can you help me out?

**Comment by gauthamzz** [comment]
https://www.youtube.com/watch?v=qjVYRDQAl2Q

**Comment by aswinzz** [comment]
@arpitmisraw  status?

**Comment by arpitmisraw** [comment]
I've finalised the basic layout of how it should be done. But it'll take me some time to implement it.

I'm planning on adding the video below the main header on button press and then removing it on pressing it again.

**Comment by gauthamzz** [comment]
Go ahead
