### ISSUE TITLE
Show issues in Opencode 

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#164]
make something similar to https://fossiiita.github.io/opencode2017/projects.html#issues

**Comment by aayushjoglekar** [comment]
Love to do it.

**Comment by gauthamzz** [comment]
assigned to @aayushjoglekar

**Comment by aayushjoglekar** [comment]
How will the issues be updated regularly?

**Comment by gauthamzz** [comment]
github will do that. you just need to fetch from the api. see the link i send. see its code to get more ideas

**Comment by aswinzz** [comment]
@gauthamzz  this issue already exists #131

**Comment by aswinzz** [comment]
i am closing this issue for now! @aayushjoglekar  comment on the old issue. if he is not able to finish then we will assign it to you!
