### ISSUE TITLE
Add projects link on navbar

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#167]
Only for first timers.
Link to the projects in the website

**Comment by abhishhh1** [comment]
I want to do this

**Comment by Divy123** [comment]
Can I do this?

**Comment by techac** [comment]
Can i do this>

**Comment by gauthamzz** [comment]
assinged to @Divy123 
@abhishhh1 one issue at a time

**Comment by Esha23** [comment]
Can I do it?

**Comment by Shivansh1805** [comment]
can i do this

**Comment by Divy123** [comment]
Resolved issue #167

**Comment by Divy123** [comment]
Is my issue Resolved....?

**Comment by pradeepgangwar** [comment]
Please allocate points to @Divy123 He solved the issue in #192 But somebody did the work in his/her PR. No reference to that.
