### ISSUE TITLE
Fix broken link in mentors 

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#173]

**Comment by amriteshbhaskar** [comment]
i would like to work on this

**Comment by gauthamzz** [comment]
assigned to @amriteshbhaskar

**Comment by aswinzz** [comment]
i dont think this issue require that much time.
anyone else can take up this issue and fix participants broken images too

**Comment by gauthamzz** [comment]
More broken links , merge properly @aswinzz @anupam-Dagar @pradeep-Gangwar @aswanthkoleri
