### ISSUE TITLE
Add cards for participant projects 

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#174]
Add cards similar for participant projects

**Comment by aadixiiita** [comment]
Can i work on this ??

**Comment by gauthamzz** [comment]
assigned t @aadixiiita

**Comment by AK-007** [comment]
Cards for projects are already added in the site.

**Comment by shivhek25** [comment]
Is this unassigned ? Can i work on this ?

**Comment by pradeepgangwar** [comment]
@shivhek25 assigned

**Comment by gauthamzz** [comment]
wait duplicate issue.

**Comment by gauthamzz** [comment]
Games are already added. Sorry for my mistake.
