### ISSUE TITLE
Make  simple JavaScript game 

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#175]
Make a JavaScript game and put links in https://github.com/opencode18/OpenCode-Collaborative/blob/master/json/game.json and send pr.  (Updated Issue) 
Both github repo link and gh pages link needed.
The games should be made after opencode started or we wont count it. Your old repo's as well.

**Comment by amriteshbhaskar** [comment]
I would like to work on this

**Comment by gauthamzz** [comment]
eveyone can work on this, no need to comment. Just post the link when done

**Comment by amriteshbhaskar** [comment]
should we mention the game we are working on such that there is no overlap

**Comment by gauthamzz** [comment]
its fine. Just make sure you make it yourself. You can overlap. The best one gets extra points at the end.

**Comment by AK-007** [comment]
Can I add a single player Tic-Tac-Toe game?

**Comment by swaager** [comment]
https://github.com/swaager/Dodger_game

**Comment by swaager** [comment]
https://github.com/swaager/Dodger_game
![game](https://user-images.githubusercontent.com/29673845/34839960-72ff67b2-f729-11e7-8f25-214ac73f5b2d.png)

**Comment by gauthamzz** [comment]
send gh pages link only

**Comment by arpitmisraw** [comment]
I'd like to work on 2048.

**Comment by AK-007** [comment]
Link to play Single player Tic-Tac-Toe : https://ak-007.github.io/Tic-Tac-Toe/

**Comment by OrionStar25** [comment]
https://orionstar25.github.io/Whack-a-Mole-game/

**Comment by gauthamzz** [comment]
@OrionStar25 you are not added in participants . looks good though

**Comment by OrionStar25** [comment]
@gauthamzz okay why am i not added in participants? :O

**Comment by gauthamzz** [comment]
@OrionStar25 your name is not in https://opencode18.github.io/OpenCode-Collaborative/ participants list. send a pr and add yourself

**Comment by Jigar3** [comment]
Simple snake game
https://github.com/Jigar3/Old-School-Snake-Game

**Comment by gauthamzz** [comment]
The games should be made after opencode started or we wont count it. Your old repo's as well.

**Comment by swaager** [comment]
https://swaager.github.io/Dodger_game/dodger.html

**Comment by nikki1016** [comment]
https://nikki1016.github.io/Color-game/

**Comment by adiagg2000** [comment]
MEMORY GAME

https://adiagg2000.github.io/memory_game/memory.html

**Comment by gauthamzz** [comment]
@swaager i wish we could move via keyboard. Its hard to click 😄

**Comment by gauthamzz** [comment]
@nikki1016 im always getting wrong answer. poor me or its always like that 😢

**Comment by gauthamzz** [comment]
good job @adiagg2000

**Comment by ananya-agrawal** [comment]
will work on a breakout game

**Comment by nikki1016** [comment]
@gauthamzz no sir,  its not always like that...
![win](https://user-images.githubusercontent.com/26041681/34892224-74b4cf04-f7fe-11e7-9017-9087501c61bf.png)

**Comment by falconis** [comment]
Can two of us contribute to a single game and get the points individually?

**Comment by swaager** [comment]
o yeah!! , soon i will fix that @gauthamzz .

**Comment by gauthamzz** [comment]
If the game is good enough both will get equal or we will divide points half way

**Comment by brain-sick** [comment]
https://brain-sick.github.io/webGame.github.io/

**Comment by aadixiiita** [comment]
https://aadixiiita.github.io/mygame/

**Comment by gauthamzz** [comment]
@aadixiiita game needs score or its not a game 😄

**Comment by aadixiiita** [comment]
It's showing the score at the bottom when Ball hits , nd after 3 seconds Page reloads for next turn ???

**Comment by ananya-agrawal** [comment]
https://ananya-agrawal.github.io/break-the-brick-game/

**Comment by ritikamotwani** [comment]
https://ritikamotwani.github.io/Tetris/

**Comment by SLakhani1** [comment]
will work on a snake game

**Comment by SLakhani1** [comment]
will work on a snake game

**Comment by MaanasVohra** [comment]
https://maanasvohra.github.io/2D-Ping-Pong-Game/

**Comment by gauthamzz** [comment]
Submit your games in the json file : games from now on
