### ISSUE TITLE
Show number of stars and forks 

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#176]

**Comment by AK-007** [comment]
I would like to work on this.

**Comment by gauthamzz** [comment]
assigned to @AK-007

**Comment by AK-007** [comment]
Should I show the stars and forks for this repository using Github API ? Also where do you want it to be displayed ?

**Comment by aswanthkoleri** [comment]
@AK-007  Refer this [link](https://buttons.github.io/)

**Comment by aswinzz** [comment]
@AK-007  place it in the upper right corner. yeah you cna use github api.
