### ISSUE TITLE
Setup Oh My Zsh on your system

### ISSUE THREAD

**Issue by mubaris** [opencode18/OpenCode-Collaborative#181]
Set up [this project](https://github.com/robbyrussell/oh-my-zsh) on your system and post screenshot of terminal

**Comment by Jigar3** [comment]
![screenshot from 2018-01-12 03-31-15](https://user-images.githubusercontent.com/32068121/34849642-12ffd156-f749-11e7-9c9e-6cd4a5acd207.png)

Theme: blinks

**Comment by surasnayak** [comment]
Done
verified by running : echo $SHELL 
RETURNED: /usr/bin/zsh
![zsh](https://user-images.githubusercontent.com/21239888/34871541-1bd67120-f7b4-11e7-9603-75ac12d0cdc2.png)
Is anything else required?

**Comment by maverick0004** [comment]
![screenshot from 2018-01-12 16-27-35](https://user-images.githubusercontent.com/33194760/34872050-8f91ab74-f7b5-11e7-9867-3ae4a1ebd264.png)

verified by running : echo $SHELL
RETURNED: /usr/bin/zsh

**Comment by adiagg2000** [comment]
VERIFIED BY running : echo $SHELL
RETURNED: /bin/zsh

![screenshot from 2018-01-12 20-20-45](https://user-images.githubusercontent.com/33027339/34880319-1de8cf18-f7d6-11e7-95ab-45c550cb33de.png)

**Comment by falconis** [comment]
![zsha](https://user-images.githubusercontent.com/30634978/34989075-145450d0-fae7-11e7-87e1-cb6deb29d600.png)

**Comment by shivhek25** [comment]
![screen shot 2018-01-25 at 3 41 26 pm](https://user-images.githubusercontent.com/24766191/35382764-427ae9fa-01e6-11e8-9e86-365c0014054c.png)

**Comment by msatul1305** [comment]
![screenshot from 2018-02-03 20-01-52](https://user-images.githubusercontent.com/24864738/35768327-1b255b7e-0920-11e8-8c14-db6b675eef4a.png)

**Comment by rahulkumaran** [comment]
![zsh](https://user-images.githubusercontent.com/26206171/35779574-3d501de4-09f5-11e8-827a-8653b6fdee9d.png)

**Comment by aayushjoglekar** [comment]
![image](https://user-images.githubusercontent.com/28949397/36063672-fdc42796-0ea5-11e8-97f2-62861cea73f8.png)
Verified using echo $SHELL
