### ISSUE TITLE
Classify projects based on languages

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#205]
You can use mixitup js.

**Comment by Jigar3** [comment]
I would like to take this issue

**Comment by mubaris** [comment]
Before implementing this, you need to finish #102 

@Jigar3 If you finish #102 you can take this

**Comment by Jigar3** [comment]
Ya I will finish #102 first

**Comment by mubaris** [comment]
@Jigar3 👍

**Comment by Jigar3** [comment]
Classification UI can be like this 
https://codepen.io/mintia/pen/MoQGRP?limit=all&page=2&q=Classify
Should I classify in this fashion

**Comment by aayushjoglekar** [comment]
@mubaris #102 was resolved and merged through PR #187. I have to fix some issues related to new project.

**Comment by mubaris** [comment]
@aayushjoglekar Few projects were added. But now we have included few more projects. @Jigar3 will work on it.

**Comment by aswinzz** [comment]
@Jigar3 status??

**Comment by Jigar3** [comment]
Please allot this issue to someone else

**Comment by surasnayak** [comment]
What exactly do we need to do.?

**Comment by aswinzz** [comment]
https://www.hackinthenorth.com/team.html something like this. It will be better if we can shift the projects to a new page and do this thing there!

**Comment by aswinzz** [comment]
@surasnayak would you like to do?

**Comment by aswinzz** [comment]
Anyone who would like to take up this issue?

**Comment by arpitmisraw** [comment]
I'd like to do this.

**Comment by aswinzz** [comment]
@arpitmisraw  are you working on this?
