### ISSUE TITLE
make contents of footer vertically center

### ISSUE THREAD

**Issue by Anupam-dagar** [opencode18/OpenCode-Collaborative#226]
After addition of color, it will not look good as content stick to top
![](https://user-images.githubusercontent.com/32304546/34869380-ba3a5686-f7ac-11e7-877b-4fcf89bdccbc.PNG)

**Comment by aayushjoglekar** [comment]
@Anupam-dagar May I work on this?

**Comment by hacker1x1x1** [comment]
Can i work on this?

**Comment by AK-007** [comment]
Can I work on this?

**Comment by Anubhav2000** [comment]
May i work on this?

**Comment by prathamprakash29** [comment]
can I work on this?

**Comment by aayushjoglekar** [comment]
@aswinzz Any updates?

**Comment by Anupam-dagar** [comment]
@aayushjoglekar assigned

**Comment by aswinzz** [comment]
@aayushjoglekar  what's the status?
