### ISSUE TITLE
Generate Github Resume

### ISSUE THREAD

**Issue by mubaris** [opencode18/OpenCode-Collaborative#23]
Opt-In for Github Resume service by staring the following project - [Repo](https://github.com/resume/resume.github.com)

After generating the resume, share your resume link to get points

Visit the project repo to read resume generating instructions

**Comment by Tlazypanda** [comment]
I would be interested to take this up.

**Comment by mubaris** [comment]
Everyone is encouraged to do this.

**Comment by madhur1998** [comment]
Do we have to comment the link here?

**Comment by aswinzz** [comment]
yes

**Comment by madhur1998** [comment]
https://resume.github.io/?madhur1998

**Comment by falconis** [comment]
[My Resume](https://resume.github.io/?falconis)

**Comment by Tlazypanda** [comment]
http://resume.github.io/?Tlazypanda

**Comment by atisayajain** [comment]
[My Github Resume](http://resume.github.io/?atisayajain)

**Comment by arpitmisraw** [comment]
https://resume.github.io/?arpitmisraw

**Comment by strikertanmay** [comment]
http://resume.github.io/?strikertanmay

**Comment by Re42** [comment]
[Yash Rathore](https://resume.github.io/?re42)

**Comment by Panda2498** [comment]
http://resume.github.io/?Panda2498

**Comment by maverick0004** [comment]
https://resume.github.io/?maverick0004

**Comment by marshallKR7** [comment]
https://resume.github.io/?marshallKR7

**Comment by GOVINDDIXIT** [comment]
https://resume.github.io/?GOVINDDIXIT

**Comment by RohanShekhawat** [comment]
http://resume.github.io/?RohanShekhawat

**Comment by jat9674** [comment]
https://resume.github.io/?jat9674

**Comment by SSPrafulTondomker** [comment]
http://resume.github.io/?SSPrafulTondomker

**Comment by prathamprakash29** [comment]
[My GitHub Resume](https://resume.github.io/?prathamprakash29)

**Comment by ananya-agrawal** [comment]
https://resume.github.io/?ananya-agrawal

**Comment by aayushjoglekar** [comment]
http://resume.github.io/?aayushjoglekar

**Comment by AK-007** [comment]
http://resume.github.io/?AK-007

**Comment by AlphaCholera** [comment]
https://resume.github.io/?AlphaCholera

**Comment by brain-sick** [comment]
https://resume.github.io/?brain-sick

**Comment by utkarshsingh99** [comment]
[About Me](https://resume.github.io/?utkarshsingh99)

**Comment by druvalcr28** [comment]
http://resume.github.io/?druvalcr28

**Comment by aadixiiita** [comment]
http://resume.github.io/?aadixiiita

**Comment by shyam49** [comment]
[Resume] (https://resume.github.io/?shyam49)

**Comment by KomalBhadani27** [comment]
https://resume.github.io/?KomalBhadani27

**Comment by adiagg2000** [comment]
https://resume.github.io/?adiagg2000

**Comment by Esha23** [comment]
https://resume.github.io/?Esha23

**Comment by swaager** [comment]
https://resume.github.io/?swaager

**Comment by 16priyesh** [comment]
https://resume.github.io/?16priyesh

**Comment by Ace-Bansal** [comment]
[My resume](https://resume.github.io/?Ace-Bansal)

**Comment by hacker1x1x1** [comment]
http://resume.github.io/?hacker1x1x1

**Comment by rahulkumaran** [comment]
[My Résumé](http://resume.github.io/?rahulkumaran)

**Comment by ProBeta1** [comment]
https://resume.github.io/?ProBeta1

**Comment by cuz789** [comment]
http://resume.github.io/?cuz789

**Comment by permanent-bnsl** [comment]
[My Resume](https://resume.github.io/?permanent-bnsl)

**Comment by surasnayak** [comment]
Link to my resume: https://resume.github.io/?surasnayak

**Comment by namantw** [comment]
http://resume.github.io/?namantw

**Comment by abhishhh1** [comment]
https://resume.github.io/?abhishhh1

**Comment by cuz789** [comment]
https://resume.github.io/?cuz789

**Comment by kgauravk** [comment]
https://resume.github.io/?kgauravk

**Comment by OrionStar25** [comment]
https://resume.github.io/?orionstar25

**Comment by shivhek25** [comment]
http://resume.github.io/?shivhek25

**Comment by nityanandagohain** [comment]
https://resume.github.io/?nityanandagohain

**Comment by ashish4321** [comment]
https://resume.github.io/?ashish4321

**Comment by anandwana001** [comment]
[GitHub Resume](https://resume.github.io/?anandwana001)

**Comment by vchrombie** [comment]
http://resume.github.io/?vchrombie

**Comment by hiteshpr** [comment]
http://resume.github.io/?hiteshpr

**Comment by SLakhani1** [comment]
https://resume.github.io/?SLakhani1

**Comment by ashispnayak** [comment]
https://resume.github.io/?ashispnayak

**Comment by ritikamotwani** [comment]
https://resume.github.io/?ritikamotwani

**Comment by piyu007** [comment]
https://resume.github.io/?piyu007

**Comment by msatul1305** [comment]
http://resume.github.io/?msatul1305

**Comment by Jigar3** [comment]
[My Resume](http://resume.github.io/?Jigar3

**Comment by likhithamannam** [comment]
https://resume.github.io/?likhithamannam

**Comment by Anjali2901** [comment]
http://resume.github.io/?Anjali2901
