### ISSUE TITLE
show number of stars and fork each project 

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#237]
use github api . should be displayed without flipping

**Comment by aadixiiita** [comment]
I would to work on this ...

**Comment by aswinzz** [comment]
@gauthamzz  duplicate issue #176

**Comment by aswinzz** [comment]
@aadixiiita status?

**Comment by aadixiiita** [comment]
Sir , i am able to get stars nd forks through api , and put in Html But as Stars and Forks are variable and fetched from api , How can i put them on flip card , As all information of flip card is Static and fixed value contained in Json file .

**Comment by aswinzz** [comment]
@aadixiiita in the  api call give the variable of repo name instead of real value.

**Comment by pradeepgangwar** [comment]
@aadixiiita still working?

**Comment by aadixiiita** [comment]
No .. i am unable to give variable in JSON file ..

**Comment by pradeepgangwar** [comment]
Looks like a tough issue i am increasing points

**Comment by AK-007** [comment]
Can I try this issue?

**Comment by pradeepgangwar** [comment]
yes go ahead.

**Comment by aswinzz** [comment]
@AK-007  status?
