### ISSUE TITLE
Add cards for particpants games

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#240]
Add links of games already made in the issue #175

**Comment by ananya-agrawal** [comment]
i will do this

**Comment by Panda2498** [comment]
Can I work on this?

**Comment by muskan6769** [comment]
can I do this

**Comment by gauthamzz** [comment]
first one gets it @ananya-agrawal 

girls please see the girls only repo . you can suggest issues and there.

**Comment by Panda2498** [comment]
Okkay

**Comment by aswinzz** [comment]
@ananya-agrawal  status?

**Comment by ananya-agrawal** [comment]
@aswinzz working on it will soon complete it

**Comment by gauthamzz** [comment]
You won’t get anymore issues until it’s done

**Comment by aswinzz** [comment]
@ananya-agrawal  this issue will be reassigned it you are not able to complete it by today!
