### ISSUE TITLE
broken mentors and add a new mentor

### ISSUE THREAD

**Issue by Anupam-dagar** [opencode18/OpenCode-Collaborative#242]
expected behaviour is that grid starts from left most side.
![screenshot from 2018-01-12 23-45-26](https://user-images.githubusercontent.com/21174572/34889146-f9a64a46-f7f2-11e7-9183-bf424b3fb8b2.png)
add this mentor:
name: Himanshu shekhar
take image from facebook
bio : i make things
you can easily find facbook, github and twitter by searching

**Comment by hacker1x1x1** [comment]
let me work on this!

**Comment by AK-007** [comment]
May I work on it?

**Comment by Anupam-dagar** [comment]
@hacker1x1x1 assigned
