### ISSUE TITLE
Make your own awesome list 

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#245]
https://github.com/sindresorhus/awesome

awesome list is a great way to find resources over github.
a list made by people will always be better than google.
So everyone make your own awesome list about anything you love.
see the present lists to see some examples. 

Once made comment in the comments. Take your time and make it slowly.
It should meet the standards. 

If your list makes it to the main awesome list you get 100 points.

**Comment by Esha23** [comment]
I will do it!!

**Comment by KomalBhadani27** [comment]
i want to do it

**Comment by surasnayak** [comment]
should I actually make a repository and make a list or just commect the file with the list here itself?

**Comment by gauthamzz** [comment]
Make a repo in your own account and do it

**Comment by surasnayak** [comment]
Below is the Link to my repository where awesome-list is made.
Please check. : )
Link: https://github.com/surasnayak/awesome-list-coding-challenge-websites

**Comment by anandwana001** [comment]
Link:- https://github.com/anandwana001/awesome-google-communities-certification
here is my awesome list. I will update it regularly

**Comment by Ace-Bansal** [comment]
Here's my [awesome list](https://github.com/Ace-Bansal/Awesome-List-Top-5-Songs-Since-2010)

**Comment by falconis** [comment]
This is my awesome [list](https://github.com/falconis/Awesome-List-Top-Novels), listing top 3 books on goodreads of various categories.

**Comment by gauthamzz** [comment]
Both approved. 
Add opencode badge in readme.

**Comment by aadixiiita** [comment]
Here;s my awesome list of Best PC game [list](https://github.com/aadixiiita/Awesome-list-best-PC-game/blob/master/README.md)

**Comment by gauthamzz** [comment]
Very less entries. 
How do you decide which is the best game.

**Comment by aadixiiita** [comment]
@gauthamzz From the IMDB rating .

**Comment by gauthamzz** [comment]
Game using IMDb 😐 add top 10 of each year based on steam or something
