### ISSUE TITLE
typo in file: PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by yashovardhanagrawal** [opencode18/OpenCode-Collaborative#248]
it should be `PULL_REQUEST_TEMPLATE`, not `PULL_RQUEST_TEMPLATE`

**Comment by yashovardhanagrawal** [comment]
you may add the label `Rookie` here

**Comment by surasnayak** [comment]
@yashovardhanagrawal can I do this?

**Comment by gauthamzz** [comment]
Yeah sure
