### ISSUE TITLE
Show all projects in issues

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#250]
For github api it’s only shown for two projects . Should be for each project in the json file.

**Comment by nityanandagohain** [comment]
i want to work on this

**Comment by pradeepgangwar** [comment]
@nityanandagohain assigned.

**Comment by aswinzz** [comment]
@nityanandagohain  status?

**Comment by gauthamzz** [comment]
This is issue is open, if anyone want can solve this.

**Comment by arpitmisraw** [comment]
I'd like to work on it

**Comment by gauthamzz** [comment]
@arpitmisraw assigned to you
