### ISSUE TITLE
Make a website for yourself

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#251]
Host on gh pages and comment link.

**Comment by surasnayak** [comment]
Can we do it only using HTML and CSS?

**Comment by gauthamzz** [comment]
Its personal website , you can make anyway you want . Don’t you site builder like wix or Wordpress . Anything else is fine

**Comment by aadixiiita** [comment]
https://aadixiiita.github.io

**Comment by brain-sick** [comment]
https://brain-sick.github.io/webGame.github.io/

**Comment by rahulkumaran** [comment]
https://rahulkumaran.github.io

**Comment by abhishhh1** [comment]
My Blog - https://abhishhh1.github.io
still in progress

**Comment by gauthamzz** [comment]
@brain-sick its supposed to be yourwebstie here . and game in diffrent post

**Comment by hacker1x1x1** [comment]
https://hacker1x1x1.github.io/

**Comment by anandwana001** [comment]
https://anandwana001.github.io/

**Comment by surasnayak** [comment]
https://surasnayak.github.io/MySpace/home.html

**Comment by vchrombie** [comment]
https://vchrombie.github.io/

**Comment by hiteshpr** [comment]
hiteshroy.me

**Comment by ananya-agrawal** [comment]
https://ananya-agrawal.github.io/anayaagrawal125.github.io/

**Comment by shivhek25** [comment]
https://shivhek25.github.io

**Comment by gauthamzz** [comment]
why is your website asking my name 😆 @shivhek25

**Comment by adiagg2000** [comment]
https://adiagg2000.github.io/my/a.html

**Comment by jat9674** [comment]
It should be a portfolio type or It can be any site that I created by own?

**Comment by gauthamzz** [comment]
It can be a personal blog or personal website . I thought it was clear .

**Comment by shivhek25** [comment]
@gauthamzz It's a feature. The website later displays your name on the header welcoming you to my website.

**Comment by mahek5** [comment]
https://mahek5.github.io/

**Comment by gauthamzz** [comment]
@shivhek25 its nice 😄 I liked it 
@mahek5  👍

**Comment by swaager** [comment]
https://swaager.github.io/Myself/

**Comment by swaager** [comment]
https://swaager.github.io/web/

**Comment by piyu007** [comment]
piyu007.github.io

**Comment by piyu007** [comment]
https://piyu007.github.io/

**Comment by ashish4321** [comment]
https://ashish4321.github.io/

**Comment by Divy123** [comment]
https://divy123.github.io/Portfolio/
