### ISSUE TITLE
Remove the gradient on hovering over the social icons on the flip cards.

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenCode-Collaborative#255]
![screenshot from 2018-01-13 14-33-07](https://user-images.githubusercontent.com/21339090/34904590-c71d1808-f86e-11e7-8ed8-7f85aed10000.png)
Remove this gradient.Just the light blue on hover as before is enough.

**Comment by pranjalg2308** [comment]
i would like to do it

**Comment by pradeepgangwar** [comment]
@pranjalg2308 assigned.

**Comment by aswinzz** [comment]
this issue is open !

**Comment by shivhek25** [comment]
I would like to work on this.

**Comment by shivhek25** [comment]
Has this been fixed ? Because there's no gradient as such when I hover over the social icons. My repo is updated.
