### ISSUE TITLE
Change the background of the landing page.

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenCode-Collaborative#26]
Make the background of the landing page to the Linear gradient backgorund used in the OpenCode Mian page : [Main page](https://opencode18.github.io/)

**Comment by Tlazypanda** [comment]
I would be interested to take this up.

**Comment by aswanthkoleri** [comment]
@Tlazypanda  You may do this !

**Comment by Panda2498** [comment]
May I change the background?

**Comment by Eunoia1729** [comment]
May I take up this issue ?
