### ISSUE TITLE
Fix stars and forks in mobile view

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#261]
![screenshot from 2018-01-13 21-24-46](https://user-images.githubusercontent.com/25057819/34905598-81710148-f882-11e7-8c33-2141063c8b59.png)

**Comment by arpitmisraw** [comment]
I would like to work on this since I'm almost finished with my previously assigned issue #163

**Comment by pradeepgangwar** [comment]
@arpitmisraw assigned

**Comment by ashraysinha6069** [comment]
i would like to work on this
