### ISSUE TITLE
Link star and fork to the github repo

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#268]
Only for new commers. To start off with opencode

**Comment by shivhek25** [comment]
I don't understand what do you exactly mean by this.

**Comment by gauthamzz** [comment]
the star and fork on the website top corner. when you click it ,redicrect to the github repository.
its a simple issue.

**Comment by shivhek25** [comment]
So basically if someone clicks on the star or fork button the top corner of the page, then it redirects to https://github.com/opencode18/OpenCode-Collaborative. Right ?

**Comment by shivhek25** [comment]
I would like to take this up in that case.
