### ISSUE TITLE
Make a chatbot 

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#271]
Create a facebook page
Create a chatbot for that page using services such as chatfuel or dialogflow or wit.ai

Make your bot do something. see bot stores to get ideas about chatbots. 

Comment link on fb page at the bottom. Share your creation to the world on fb and tag opencode page. 😄 (that link also comment)
The bots which stands out will get extra credits. Depending on your implementation and creativity.

Atleast 5-6 type actions. If no text reply is also fine, given its fun.

**Comment by swaager** [comment]
i want to do it!!!

**Comment by gauthamzz** [comment]
Issue is for everyone

**Comment by Ajay2007** [comment]
Sir I would like to take this issue.

**Comment by aswinzz** [comment]
@Ajay2007  it is for everyone :disappointed:

**Comment by ananya-agrawal** [comment]
https://www.facebook.com/Jane-2020199884928709/
tried making one will make a better one in future

**Comment by rahulkumaran** [comment]
can we make a chatbot using python and run it on telegram for this issue?

**Comment by gauthamzz** [comment]
Yeah anything you wish is fine

**Comment by rahulkumaran** [comment]
@gauthamzz should it only be a conversation bot or can it also be a bot that performs some functions? like finding cricket scores and all?

**Comment by gauthamzz** [comment]
yeah anything is fine.

**Comment by rahulkumaran** [comment]
@gauthamzz I've created a chatbot on telegram called "UtlyzMeBot"
You can test it by typing the name of the bot(mentioned above and execute the commands it gives as of now)
Also, if you use the fb functionality of the bot, the first time it might not let you access! but your account will get a notif saying suspicious login activity. If you click on "this was me", and try running the fb command again, it'll work perfectly!

**Comment by gauthamzz** [comment]
@aswinzz check this
