### ISSUE TITLE
Give hover effect to social Icons on the flip cards.

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenCode-Collaborative#28]
When hovered over the icons, the color of the icon should change to Light blue color.

**Comment by falconis** [comment]
Can I work on this?

**Comment by mubaris** [comment]
Go ahead @falconis

**Comment by strikertanmay** [comment]
can i also work on it..??

**Comment by aayushjoglekar** [comment]
Can I contribute to this issue?
