### ISSUE TITLE
Fix trailer window

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#281]
the player window is not visible completely.

**Comment by Ace-Bansal** [comment]
may i work on this?

**Comment by aswinzz** [comment]
sure!

**Comment by KomalBhadani27** [comment]
i want to work on this

**Comment by pradeepgangwar** [comment]
@KomalBhadani27 sorry but @Ace-Bansal was the first to ask here. You can always pick other issues on any repo.

**Comment by KomalBhadani27** [comment]
Sure. I know. Not need to say sorry. I know he asked first.
