### ISSUE TITLE
Make each heading as same as issues heading

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#282]
![](https://user-images.githubusercontent.com/28949397/34894933-6d84e506-f809-11e7-8272-8f309a8ba34a.png)

**Comment by priyanka-choubey** [comment]
i want to work on this.

**Comment by aswinzz** [comment]
@priyanka-choubey  you can work on this.

**Comment by aswinzz** [comment]
Issue is reassigned! anyone can take up this issue

**Comment by shivhek25** [comment]
Can you specify what exactly do you want ? I can work on this then

**Comment by AK-007** [comment]
I would like to work on this.
