### ISSUE TITLE
Trailer text color in navbar does not match other navbar items color

### ISSUE THREAD

**Issue by pradeepgangwar** [opencode18/OpenCode-Collaborative#287]
![screenshot-2018-1-14 opencode 1](https://user-images.githubusercontent.com/21259802/34914165-d349bfe0-f932-11e7-815b-440ff3e4731a.png)

**Comment by KomalBhadani27** [comment]
i want to do this

**Comment by pradeepgangwar** [comment]
assigned

**Comment by KomalBhadani27** [comment]
The colour is different because the target trailer window is in the first page only. When we scroll to other section of the page the rest of the navbar items' colour changes accordingly.

**Comment by pradeepgangwar** [comment]
But we aren't either focused to trailer ... probably it can be fixed by removing the bootstrap classes from link and that of trailer window. Or renaming them such that both (navbar link and trailer window) have different class names.

**Comment by KomalBhadani27** [comment]
Okay I will do it.

**Comment by prathamprakash29** [comment]
I would like to work on this.

**Comment by pradeepgangwar** [comment]
@prathamprakash29 assigned.

**Comment by pradeepgangwar** [comment]
This issue has no meaning since now navbar is hidden on landing page.
