### ISSUE TITLE
disable link highlighting when hovering over to fork and stars and redirect to new tab

### ISSUE THREAD

**Issue by pradeepgangwar** [opencode18/OpenCode-Collaborative#288]
Currently when we hover to fork and stars it highlights it which is default property of anchor tag. We wish to disable that to keep it simple. Also on clicking it link should open in new tab instead of same tab.

![screenshot from 2018-01-14 14-09-29](https://user-images.githubusercontent.com/21259802/34914260-111be274-f935-11e7-8d72-7c39f261a1bd.png)

**Comment by arpitmisraw** [comment]
I'd like to work on this.

**Comment by Esha23** [comment]
I would like to work on it.

**Comment by pradeepgangwar** [comment]
@arpitmisraw you are working on #261. Would you mind giving this to @Esha23

**Comment by muskan6769** [comment]
can I do it

**Comment by KomalBhadani27** [comment]
i want to do this

**Comment by pradeepgangwar** [comment]
assigned to @Esha23 as @arpitmisraw already has a issue assigned i.e. #261

**Comment by arpitmisraw** [comment]
I solved #261 . But it's fine. I'll take up another one in the future. :smiley:
