### ISSUE TITLE
Fix alignment

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#289]
Make it centered
![screenshot from 2018-01-14 14-59-05](https://user-images.githubusercontent.com/25057819/34914605-b5872b38-f93b-11e7-9642-543e0e143c5e.png)

**Comment by KomalBhadani27** [comment]
i want to do it

**Comment by abhishhh1** [comment]
I m working on it

**Comment by abhishhh1** [comment]
Sir, I've solved this issue

**Comment by pradeepgangwar** [comment]
@aswinzz it was centered but @Anupam-dagar created a issue after which it was center aligned.

**Comment by ashraysinha6069** [comment]
i would like to work on this issue

**Comment by aswinzz** [comment]
@pradeepgangwar so shall we assign someone?

**Comment by pradeepgangwar** [comment]
@aswinzz sure. Do it.

**Comment by Ace-Bansal** [comment]
may I work on this then?

**Comment by Anupam-dagar** [comment]
@pradeepgangwar i remember creating an issue for centering it :stuck_out_tongue: 
@Ace-Bansal assigned

**Comment by gauthamzz** [comment]
Solve this issue fast,the website looks bad.

**Comment by Ace-Bansal** [comment]
@gauthamzz on it
