### ISSUE TITLE
Add FOSSIIITA,IIITA and GeekHaven logo.

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenCode-Collaborative#29]
Add the following logos on the right side of the footer.Similar,to that seen in the Main page : [OpenCode](https://opencode18.github.io)

**Comment by aadixiiita** [comment]
I would like to work on this issue

**Comment by aswinzz** [comment]
@aadixiiita  solve the issues that you have been assigned

**Comment by Tlazypanda** [comment]
Can I work on this?I have made a pull request for my previous issue.

**Comment by mubaris** [comment]
@Tlazypanda Sure

**Comment by aayushjoglekar** [comment]
Can I work on this issue?

**Comment by prathamprakash29** [comment]
I would like to work on this issue
