### ISSUE TITLE
Add social links of opencode in the footer 

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#30]
add facebook,email,github icons to the footer.
Right side is preferable.

**Comment by aadixiiita** [comment]
I would like to work on this issue

**Comment by mubaris** [comment]
@aadixiiita You can take this

**Comment by jat9674** [comment]
can i get chance to work on this issue?

**Comment by ToughDude** [comment]
can i work on this issue?
