### ISSUE TITLE
Make site uniform 

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#301]
The color of the site is very diffrent for diffrent parts. Try to make the colors uniform.

**Comment by KomalBhadani27** [comment]
i would do it

**Comment by Esha23** [comment]
Can I try?

**Comment by gauthamzz** [comment]
assigned to @KomalBhadani27

**Comment by aswinzz** [comment]
@KomalBhadani27  status?

**Comment by aswinzz** [comment]
issue is open for others

**Comment by arpitmisraw** [comment]
I'd like to do it.

**Comment by gauthamzz** [comment]
ok

**Comment by aswinzz** [comment]
@arpitmisraw  status?

**Comment by arpitmisraw** [comment]
I haven't had the time to work on it much. But I'd still like to continue.

**Comment by arpitmisraw** [comment]
I'm on it right now.

**Comment by aswinzz** [comment]
@arpitmisraw  status?

**Comment by shivhek25** [comment]
Has this issue been solved  ? @aswinzz  I would like to work on it if it's reassigned.

**Comment by arpitmisraw** [comment]
It's okay if @shivhek25 works on it, @aswinzz .

**Comment by shivhek25** [comment]
@gauthamzz Could you please elaborate more on the issue ? I find the colours to be uniform throughout the document.

**Comment by shivhek25** [comment]
@gauthamzz @aswinzz ?
