### ISSUE TITLE
Increase speed of loading the website

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#308]
refer google developers. Get a score above 75 atleast.

Resize all images, minify files which wont be ever changed. Keep both min and non minified but link only to the minified version

**Comment by falconis** [comment]
I'd like to take this.

**Comment by gauthamzz** [comment]
assigned to @falconis

**Comment by falconis** [comment]
Which software should I use to resize the images?

**Comment by falconis** [comment]
I brought up the score from 45 to 72 by resizing the images. Will that do? As can't think of any other way to improve the score, since all linked files are also minified.

**Comment by gauthamzz** [comment]
yeah thats enough for now
