### ISSUE TITLE
Share solved issues in social medias which have "social" label

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#31]
share the issues which you have solved and that have "social" label on it
  give a link and screenshot in the comments.

**Comment by aayushjoglekar** [comment]
![image](https://user-images.githubusercontent.com/28949397/34776455-03b07500-f63d-11e7-9eb6-7588cdaed834.png)

**Comment by falconis** [comment]
Is this for everyone?

**Comment by aswinzz** [comment]
@aayushjoglekar  you should share "only after you solve the issue with social label"!!

**Comment by aswinzz** [comment]
@falconis yes

**Comment by Ace-Bansal** [comment]
![screenshot 25 _li](https://user-images.githubusercontent.com/34866483/34913304-28699c3e-f91f-11e7-9115-6dedbc7b52a5.jpg)

**Comment by Re42** [comment]
https://www.facebook.com/yash.re.10/posts/1382939188502469
![image](https://user-images.githubusercontent.com/33805964/35282173-cbee2c28-007a-11e8-9563-f79553d044c5.png)

**Comment by falconis** [comment]
![toppling](https://user-images.githubusercontent.com/30634978/36043167-5f749ece-0df4-11e8-8507-1af4da3f5958.png)
