### ISSUE TITLE
Use github student pack and using .me domain create a portfolio website

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#313]
Using your college id you can avail github student pack which gives lot of offers one among them is free .me domain, use that and link it to your portfolio website.
Link the website created in #251 to the .me domain

Comment down the links below.

**Comment by vchrombie** [comment]
http://vchrombie.me/

**Comment by adiagg2000** [comment]
http://aditiagg2000.me/my/a.html

**Comment by aadixiiita** [comment]
https://aadishukla.me

**Comment by mahek5** [comment]
https://mahek5.github.io/

**Comment by Ace-Bansal** [comment]
[http://ekanshbansal.me/](http://ekanshbansal.me/)

**Comment by ananya-agrawal** [comment]
http://ananyaa.me/

**Comment by swaager** [comment]
http://swaager.me/
