### ISSUE TITLE
Add New Projects from Go Students

### ISSUE THREAD

**Issue by mubaris** [opencode18/OpenCode-Collaborative#315]
Visit https://github.com/gostudent and add all the projects which are not available on the website.

**Only Add Projects which have opencode18 label**

**Comment by nikki1016** [comment]
can I do this?

**Comment by mubaris** [comment]
@nikki1016 If you don't have any other issue assigned, Go ahead

**Comment by nikki1016** [comment]
okh ...I will.. :+1:

**Comment by nikki1016** [comment]
is this project(https://github.com/gostudent/gostudent.github.io) also to be included ?
There are no issues and PRs opened but a closed issue was labelled as Opencode18

**Comment by mubaris** [comment]
Do not add that
