### ISSUE TITLE
Add a simple Pre-Loader for the website.

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenCode-Collaborative#32]
Share it on social network and earn 10 points !
 Comment on issue #31 along witht the screenshot to get your marks verified. :smile:

**Comment by Re42** [comment]
I would like to work on this.

**Comment by atisayajain** [comment]
I would like to work on this.

**Comment by aswinzz** [comment]
@Re42  you can work on this

**Comment by ToughDude** [comment]
i would like to work on it

**Comment by ashraysinha6069** [comment]
i would like to work on it
