### ISSUE TITLE
The trailer won't stop playing after it's closed

### ISSUE THREAD

**Issue by arpitmisraw** [opencode18/OpenCode-Collaborative#321]
I had added the trailer functionality but had taken care of trailer not playing once it was closed. Somehow, there's now a bug and it still plays.

Also, can I work on it? I have one issue assigned- #250 , but I think I can solve both .

**Comment by aayushjoglekar** [comment]
I would like to work on this.

**Comment by aswinzz** [comment]
@aayushjoglekar assigned
