### ISSUE TITLE
Update scores.json

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#325]
This issue is for everyone, Update your scores in `scores.json` present in `json` folder. Follow the format given in readme while updating your marks.
Mentors will be reviewing the scores.If we find any mismatch in your scores negative marks will be given!.

**Comment by surasnayak** [comment]
What about those issues which only needed to comment a SS. Do we leave the pr blank?

**Comment by aswinzz** [comment]
yeah!

**Comment by shivhek25** [comment]
What do we mention if we have referred somebody ? Does that get counted automatically or are we supposed to mention that somewhere ?

**Comment by aswinzz** [comment]
@shivhek25  yeah you have to mention referral and the link should be their pr
