### ISSUE TITLE
make a leaderboard

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#326]
Similar to the one in this https://github.com/fossiiita/opencode2017

**Comment by Esha23** [comment]
I will try..

**Comment by gauthamzz** [comment]
@Esha23 Sure. Make sure you do this issue fast. This is a priority and will take time.

**Comment by aayushjoglekar** [comment]
I will do this.

**Comment by aswinzz** [comment]
@Esha23  status?

**Comment by Esha23** [comment]
Not completed yet!!!

**Comment by aswinzz** [comment]
Anyone who is interested in this issue?

**Comment by Anupam-dagar** [comment]
@Esha23 unassigned, this issue is now open

**Comment by aayushjoglekar** [comment]
I would like to work on this. (y)

**Comment by pradeepgangwar** [comment]
reassigned to @aayushjoglekar

**Comment by pradeepgangwar** [comment]
Closing via #394
