### ISSUE TITLE
Make preloader Opencode logo

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#332]
Animation should be thier on opencode logo

**Comment by falconis** [comment]
Can I take this? Since I'm about submit a PR.

**Comment by aadixiiita** [comment]
I would like to work on it ..

**Comment by aayushjoglekar** [comment]
I would like to do this

**Comment by gauthamzz** [comment]
you have too many issues already @falconis 
@aadixiiita you can do it

**Comment by ananya-agrawal** [comment]
just need to add svg of open code?

**Comment by gauthamzz** [comment]
yeah

**Comment by aswinzz** [comment]
@aadixiiita  status?
