### ISSUE TITLE
Share on Social Media

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#348]
Share the cool things you make in Opencode regardless of the repo it is in. Anything you make which you think is cool,share them 😄 

Tag Opencode page on Facebook. 
Post Screenshots or links of posts.

**Comment by falconis** [comment]
![social](https://user-images.githubusercontent.com/30634978/35194127-f3bb7ede-fed3-11e7-9f29-cf174167f948.png)

**Comment by falconis** [comment]
![social](https://user-images.githubusercontent.com/30634978/35194139-399c31a0-fed4-11e7-8895-85dac47ef3f7.png)

**Comment by hacker1x1x1** [comment]
https://user-images.githubusercontent.com/34509429/35372226-9555550a-014d-11e8-9a34-fda56c95a152.png

**Comment by hacker1x1x1** [comment]
![35372226-9555550a-014d-11e8-9a34-fda56c95a152](https://user-images.githubusercontent.com/34509429/35373452-4b99d6f6-0153-11e8-885c-f25c3b835cfa.png)

**Comment by Jigar3** [comment]
![screenshot_2018-02-10-23-01-39-408_com facebook katana](https://user-images.githubusercontent.com/32068121/36064791-a093a2ca-0eb6-11e8-9562-67998dbfde7f.png)
![screenshot_2018-02-10-23-01-35-879_com facebook katana](https://user-images.githubusercontent.com/32068121/36064792-a2145df6-0eb6-11e8-8d0a-ee789e796aa4.png)
![screenshot_2018-02-10-22-59-22-021_com facebook katana](https://user-images.githubusercontent.com/32068121/36064795-accea2f6-0eb6-11e8-8374-c01769c02964.png)
