### ISSUE TITLE
Add bg card for projects or apply some animation

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#355]
Projects cards look dull with only orange. Apply either images or do some effect using css.

Images should be compressed

**Comment by shivhek25** [comment]
I can work on it but most of the time the project cards or the participant cards don't load, i.e. they aren't visible.

**Comment by gauthamzz** [comment]
They don’t load when there is an error with the json

**Comment by shivhek25** [comment]
![screen shot 2018-01-24 at 1 00 57 am](https://user-images.githubusercontent.com/24766191/35296456-16134370-00a2-11e8-9381-7f68e5ba94c6.png)
You are referring to these cards, aren't you ?

**Comment by gauthamzz** [comment]
Yes

**Comment by aswinzz** [comment]
@shivhek25  status?

**Comment by shivhek25** [comment]
Working on it. @aswinzz

**Comment by aswinzz** [comment]
@shivhek25 are you working on it?

**Comment by ashish4321** [comment]
i would like to work on it if it is reassigned
