### ISSUE TITLE
Fix Github API using features in page.

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenCode-Collaborative#356]
The stars and forks are not being shown in the website. Also the Issues are also not being loaded.There is some fault in the Github API calling.Once Fixing that problem will solve this issue.

**Comment by Ace-Bansal** [comment]
May I work on this?

**Comment by hacker1x1x1** [comment]
Can I work on this issue?

**Comment by AK-007** [comment]
@aswanthkoleri May I work on this issue?

**Comment by pradeepgangwar** [comment]
@Ace-Bansal assigned.
