### ISSUE TITLE
smooth share for facebook share on right side

### ISSUE THREAD

**Issue by Anupam-dagar** [opencode18/OpenCode-Collaborative#358]
currently when you hover on it, it just reveals page details without any smooth slide animation.

**Comment by MaanasVohra** [comment]
Can I work on this issue?

**Comment by Anupam-dagar** [comment]
get yourself a room in GH first :stuck_out_tongue:

**Comment by MaanasVohra** [comment]
One of the mentors will have to create an issue for that :p

**Comment by Anupam-dagar** [comment]
Sorry but nobody will be able to create a PR for that :stuck_out_tongue:

**Comment by pradeepgangwar** [comment]
@MaanasVohra assigned.

**Comment by Anupam-dagar** [comment]
@MaanasVohra sorry my mistake, I was moderating Girls Who Code repo last night, then saw the comment and thought it to be in same repo. :stuck_out_tongue:

**Comment by pradeepgangwar** [comment]
Pr is merged.
