### ISSUE TITLE
add a reading progress bar to the page

### ISSUE THREAD

**Issue by Anupam-dagar** [opencode18/OpenCode-Collaborative#359]

**Comment by swaager** [comment]
I want to do this

**Comment by pradeepgangwar** [comment]
@swaager assigned.

**Comment by shivhek25** [comment]
Has this issue been solved ? @pradeepgangwar And what does 'reading progress bar' mean ?

**Comment by pradeepgangwar** [comment]
No the PR that referenced it is closed. So you can work on this.

**Comment by shivhek25** [comment]
Okay but what is exactly required ?

**Comment by pradeepgangwar** [comment]
@shivhek25 As you scroll down the site there should be a progress bar that tracks how much down you have scrolled. It should be below nav bar and fills fully when we have scrolled to bottom. https://blog.ghost.org/zapier-x-ghost/ See this link.
