### ISSUE TITLE
Add all particiapant Games in cards

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#361]
Add in the Json file for game and change the url in this line https://github.com/opencode18/OpenCode-Collaborative/blob/master/js/game.js#L7
to our main repo

**Comment by ananya-agrawal** [comment]
i will do this

**Comment by gauthamzz** [comment]
ok

**Comment by ananya-agrawal** [comment]
@gauthamzz  done
