### ISSUE TITLE
Add paralax effect on opencode logo

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#378]
https://www.hackinthenorth.com/ we need something like this on opencode logo!

**Comment by aadixiiita** [comment]
I would like take this one ... Tell me Parralax effect on landing page logo ???

**Comment by aswinzz** [comment]
@aadixiiita 
 yeah landing page one

**Comment by gauthamzz** [comment]
@aswinzz people are making pr very different from what you have in mind, write descriptions and examples. See this pr

**Comment by aswinzz** [comment]
@aadixiiita status?

**Comment by aadixiiita** [comment]
I m not getting exact way of doing this ... Pass this to someone else ...

**Comment by shivhek25** [comment]
I would like to work on this.

**Comment by gauthamzz** [comment]
ok

**Comment by shivhek25** [comment]
Please reassign. I don't understand what has to be done.

**Comment by gauthamzz** [comment]
See th code. It’s simple. Add parallax.js in the bottom. 

Take the image and split into different components. Add the x of each in different value . So that when the mouse moves each moves in different speed. See the same code in hack in the north repo.

**Comment by shivhek25** [comment]
Okay, I will try again. @gauthamzz

**Comment by gauthamzz** [comment]
see https://github.com/HackInTheNorth/hackinthenorth.github.io/blob/master/index.html#L87
and https://github.com/HackInTheNorth/hackinthenorth.github.io/blob/master/index.html#L530

**Comment by shivhek25** [comment]
The thing is that they have different components in the image. The gears, the mountain, etc. but opencode's logo is one whole image.

**Comment by gauthamzz** [comment]
yes, use an image editor like gimp or photoshop and cut into small induvijual components, a web dev should know a bit of image editing 😄

**Comment by shivhek25** [comment]
I have never used photoshop or gimp and it won't be possible right now to learn those softwares from scratch. Could we not just move this whole image when the cursor is hovered over it just like in hackinthenorth webpage ?

**Comment by gauthamzz** [comment]
wait ill get that done for you 😄

**Comment by shivhek25** [comment]
Thank you. That would be quite helpful. :)

**Comment by gauthamzz** [comment]
Closing since event is almost over
