### ISSUE TITLE
add svg animation for opencode logo

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#379]
it should be like this : https://codepen.io/ananya-agrawal/pen/LeMqda -  in the loader.

**Comment by hacker1x1x1** [comment]
i would like to do this

**Comment by aswinzz** [comment]
@hacker1x1x1  yeah

**Comment by aswinzz** [comment]
@hacker1x1x1  replace the loader logo ok! not the landing page one
