### ISSUE TITLE
Change the color scheme of issues section

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#380]
![deepinscreenshot_20180121221825](https://user-images.githubusercontent.com/25057819/35196519-16f06e08-fef9-11e7-9405-6d25d0e8ccf5.png)
Remove the gradient from the issues section.
NOTE: the color scheme of only the issues section should be changed! .

**Comment by aayushjoglekar** [comment]
I would work on this.

**Comment by shivhek25** [comment]
Should it appear similar to the background colour, i.e., white then ?

**Comment by aswinzz** [comment]
@shivhek25  status?

**Comment by shivhek25** [comment]
I have already created a PR. It has been checked recently and I am waiting for approval. @aswinzz

**Comment by shivhek25** [comment]
Kindly check the updated PR. @aswinzz @pradeepgangwar @gauthamzz @Anupam-dagar

**Comment by shivhek25** [comment]
Kindly check the updated PR. @aswinzz @pradeepgangwar @gauthamzz @Anupam-dagar

**Comment by shivhek25** [comment]
Kindly check @gauthamzz

**Comment by shivhek25** [comment]
@gauthamzz @aswinzz @pradeepgangwar @Anupam-dagar Could any of you kindly check the updated PR please ?
