### ISSUE TITLE
Add a view more button

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#395]
Add a new feild in json (In particpants and mentors ) called featured with binary values 1(true) or 0(false). At max 8 people(Use first 8 for now).

If a person is featured make him visible on the page when page is first loaded and there should be a view more button. When that button is clicked show everyone else in the list.

**Comment by Ace-Bansal** [comment]
I've created a PR for the issue that I was working on. May I work on this now?

**Comment by gauthamzz** [comment]
You can,if all are merged.

**Comment by ashraysinha6069** [comment]
can i work on it

**Comment by gauthamzz** [comment]
Yeah

**Comment by ashraysinha6069** [comment]
do I have to create field manually for each mentor and participant in json file or is there another way

**Comment by gauthamzz** [comment]
you need to, if you can figure out some other way,its fine with me.

**Comment by arpitmisraw** [comment]
I'd like to work on it.

**Comment by arpitmisraw** [comment]
If no one else is working, that is.

**Comment by gauthamzz** [comment]
yeah siure

**Comment by aswinzz** [comment]
@arpitmisraw please complete other issues that you have been assigned
