### ISSUE TITLE
issues section giving 403 forbidden error in console.

### ISSUE THREAD

**Issue by Anupam-dagar** [opencode18/OpenCode-Collaborative#399]
This makes no issue available on website.

**Comment by shivhek25** [comment]
Could you please explain what do you mean or maybe upload a screenshot ?

**Comment by Anupam-dagar** [comment]
when you load the website, open console in developer tools, you will find github api request is giving error
![screenshot from 2018-01-23 20-22-01](https://user-images.githubusercontent.com/21174572/35282347-43cf348a-007b-11e8-819e-71093f0b6689.png)

**Comment by Divy123** [comment]
I want to work on this issue
