### ISSUE TITLE
Show all contributions of the participants

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#414]
![deepinscreenshot_20180124204500](https://user-images.githubusercontent.com/25057819/35339784-77cedd36-0147-11e8-914b-3f4f63dec8ec.png)
When we click on the user a dropdown should come which displays the contribution and its link.

**Comment by aayushjoglekar** [comment]
I will do this.

**Comment by aswinzz** [comment]
sure @aayushjoglekar

**Comment by gauthamzz** [comment]
Is this done :/

**Comment by aayushjoglekar** [comment]
@gauthamzz Sorry for delay, I will make a PR ASAP.

**Comment by gauthamzz** [comment]
Ok
