### ISSUE TITLE
Fix trailer

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#415]
![screenshot-2018-1-24 opencode 1](https://user-images.githubusercontent.com/25057819/35340117-4e0a1082-0148-11e8-945a-2ee7b7580a8b.png)
When we play the trailer, thumbnail comes up in the top right corner. remove this. And also fix the issue when video is stopped the audio still plays.

**Comment by Ace-Bansal** [comment]
I'd like to work on this

**Comment by aswinzz** [comment]
@Ace-Bansal  assigned

**Comment by darshan934** [comment]
hi, since there has been no reponse from @Ace-Bansal can I work on this?

**Comment by aswinzz** [comment]
@darshan934  sure

**Comment by shivhek25** [comment]
Can I work on this if it is reassigned  ? @aswinzz
