### ISSUE TITLE
Remove the grey background color in the mentors section

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#416]
![deepinscreenshot_20180124205340](https://user-images.githubusercontent.com/25057819/35340297-bab2a618-0148-11e8-8943-78b001f3bea2.png)

**Comment by Tlazypanda** [comment]
I would be interested

**Comment by aswinzz** [comment]
@Tlazypanda  assigned

**Comment by shivhek25** [comment]
I would like to work on this if @Tlazypanda drops it later.
