### ISSUE TITLE
Fix scores.json file

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#423]

**Comment by Tlazypanda** [comment]
I would be interested

**Comment by gauthamzz** [comment]
sure

**Comment by shivhek25** [comment]
What does that even mean ?

**Comment by gauthamzz** [comment]
See number of people’s scores added and see the ones which are visible . Someone added bad formatting and data is not coming

**Comment by Jigar3** [comment]
I think everyone should first verify their updated scores.json using any online Linting tool.
Maybe like https://jsonlint.com
So that bad formatting can be avoided

**Comment by gauthamzz** [comment]
Yeah , I’ll add a continuous integration for that

**Comment by shivhek25** [comment]
@gauthamzz Yes, I found the problem. But another PR of mine is yet to be merged so if I commit the changes right now, that commit gets added automatically to that particular PR, right ? How do I create a separate PR while the other PR is open as well ?

**Comment by gauthamzz** [comment]
use branches 
git checkout -b somebranch 
then git push somebranch master instead.

**Comment by jayantsaraf** [comment]
i would like to work on this issue

**Comment by gauthamzz** [comment]
It’s already been assigned

**Comment by shivhek25** [comment]
Has this issue been solved ? @gauthamzz
