### ISSUE TITLE
fix scores.json cross origin request

### ISSUE THREAD

**Issue by Anupam-dagar** [opencode18/OpenCode-Collaborative#433]
since we are now using a http domain, cross origin request to json files can't be sent, on opening leaderboard, no scores are shown, to reproduce the error just see console in developer tools.

**Comment by Jigar3** [comment]
I would like to take this issue

**Comment by aswanthkoleri** [comment]
@Jigar3  You are assigned

**Comment by Jigar3** [comment]
Any hints as how I could rectify this

**Comment by Jigar3** [comment]
In scores.json, the scores property is repeated twice causing the problem i guess

**Comment by Anupam-dagar** [comment]
Since the new domain uses a http protocol instead of https,we can't request
a file directly.

**Comment by Jigar3** [comment]
https://jigar3.github.io/OpenCode-Collaborative/leaderboard 
is this correct?

**Comment by Jigar3** [comment]
@gauthamzz please can you have a look

**Comment by gauthamzz** [comment]
yeah,send pr
