### ISSUE TITLE
Fix the Mentors,Participants and Games section ASAP

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenCode-Collaborative#435]
The above mentioned sections are not loading and needs to fixed urgently.You can check the previous PR's to know what is the problem.

**Comment by hacker1x1x1** [comment]
i think there was some css style inside the index.html file, which now has been removed!
or... when this PR was merged... it had the same problem in live link- https://github.com/opencode18/OpenCode-Collaborative/pull/422

**Comment by Jigar3** [comment]
i would like to take this issue

**Comment by Jigar3** [comment]
https://jigar3.github.io/OpenCode-Collaborative/ 
is this correct?

**Comment by hacker1x1x1** [comment]
Also, the project section needs to be fixed!
@aswanthkoleri

**Comment by Jigar3** [comment]
@gauthamzz  also check out this please
