### ISSUE TITLE
Make a project of your own

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#448]
This issue will be part of your final evaluation and this will be considered as one of the deciding factors of your winning of opencode.

Create a project using any language as you wish.

You can make anything from hacks to small libraries. Don't forget to add opencode badge to your readme file. Readme should be written in a proper way as well. On how to install and use. 

Comment the link.

Make sure you spend a good amount of time, if you get a :-1: by mentors on your project,it wont be considered.

**Comment by shivhek25** [comment]
How do we add a badge to a readme file ? Also, can it be a project that I have developed recently but before opencode started ?

**Comment by aashutoshrathi** [comment]
We just need to add a badge to our repo and share the link, right?

**Comment by aashutoshrathi** [comment]
What about the ownership of that project? I mean we can still showcase it as our project, right?

**Comment by gauthamzz** [comment]
It is your own project, you will make in your own repo only. we just want to promote open source development.

**Comment by shivhek25** [comment]
https://github.com/shivhek25/Online-Exam-System

**Comment by gauthamzz** [comment]
It’s too simple and you made it a month ago

**Comment by shivhek25** [comment]
That isn't allowed ? @gauthamzz

**Comment by gauthamzz** [comment]
You should make now. That’s he point of issue . You make after issue is made

**Comment by rahulkumaran** [comment]
how many points is this for?

**Comment by gauthamzz** [comment]
@rahulkumaran Atleast 50. If we like your project we can award you more points and they can go upto a very large number.

**Comment by aashutoshrathi** [comment]
Do [this](https://github.com/aashutoshrathi/Insta-Downloader-Extension) qualify?

**Comment by gauthamzz** [comment]
@aashutoshrathi It was made a month ago, so no .

**Comment by aashutoshrathi** [comment]
Its core work was done during the period of OpenCode.

**Comment by gauthamzz** [comment]
Lemme review that for you and consider it, we will let you know if we can approve it or not in a couple of days.Since your project requires a significant amount of difficulty,if we feel like you did a lot of work on it. We could consider it. I'll let you know soon. @aashutoshrathi . Meanwhile you need to add opencode badge in your readme.

**Comment by aayushjoglekar** [comment]
@gauthamzz 

Squash : 
A Google Chrome Extension

An emergency panic button which closes all the tabs in current window, saves the URLs which can be restored later.

https://chrome.google.com/webstore/detail/squash/dopcekjfmhpiigjmijblfpklmicephec

![image](https://user-images.githubusercontent.com/28949397/35977488-3d494de0-0d09-11e8-828c-e644c5ea7e25.png)

Github Repo : 

https://github.com/aayushjoglekar/squash-chrome-extension

**Comment by gauthamzz** [comment]
Looks good

**Comment by aayushjoglekar** [comment]
@gauthamzz Any suggestions?

**Comment by AK-007** [comment]
@gauthamzz 
https://github.com/AK-007/SideJump

**Comment by rahulkumaran** [comment]
@gauthamzz , this is my project which I've been working on and I will continue to work on for a while. This is a telegram bot which has been deployed to the server and works right now too. Please have a look at this project :smile:
https://github.com/rahulkumaran/UtlyzMeBot

**Comment by aadixiiita** [comment]
@gauthamzz ,Certificate-Generator is a simple tool for creating a Certificate for an event.Currently It is set for OpenCode'18 event.You just have to simply fill the data required and click on GENERATE . I will improve it by adding more Themes, Designs and Features in This Certificate Generator.It is Made using HTML,CSS and JS.

Link -: http://aadishukla.me/Certificate-Generator/

**Comment by Anupam-dagar** [comment]
@aadixiiita it still needs improvement, maybe you can add a pdf download format.

**Comment by Anupam-dagar** [comment]
@rahulkumaran @AK-007 going by the readme, it looks good but for the complete review you need to wait a little

**Comment by gauthamzz** [comment]
The other two of @ak-007 and @rahulkumaran is approved.

**Comment by aadixiiita** [comment]
Okk .. I'll improve it ..☺☺

**Comment by Jigar3** [comment]
[TrackMyParcelAPI](https://github.com/Jigar3/TrackMyParcelAPI)
Read More About It [here](https://github.com/Jigar3/TrackMyParcelAPI#trackmyparcelapi)

**Comment by Anupam-dagar** [comment]
LGTM, what say @gauthamzz

**Comment by gauthamzz** [comment]
It’s okay 👌
