### ISSUE TITLE
Make cards for participant blogs

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#454]

**Comment by hacker1x1x1** [comment]
I can take this up!

**Comment by gauthamzz** [comment]
Ok

**Comment by hacker1x1x1** [comment]
The cards will have the photo of contestant in the front and his blog written on the back? Or something else?(kindly explain what do i put on back of the card)

**Comment by gauthamzz** [comment]
no , just make a folder for particapnt to add his images for blogs.

**Comment by hacker1x1x1** [comment]
Okay

**Comment by hacker1x1x1** [comment]
Is issue #456 different?

**Comment by gauthamzz** [comment]
Ian this done , we need it done asap

**Comment by hacker1x1x1** [comment]
My laptop is at repair😔... Hard drive became corrupt!
Anyone else can take up the issue!

**Comment by Ace-Bansal** [comment]
I'll do it

**Comment by gauthamzz** [comment]
Do this fast. Add the blogs in the other issue.
