### ISSUE TITLE
update your scores in scores.json

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#468]
those who does not update the scores will not be eligible for final judgement.

**Comment by shivhek25** [comment]
Could you help me out with something ? I have 2 PRs open in 2 repos (OpenNews and CodeStash) for quite a long time. Could you do something about it ? The mentors haven't been replying. @aswinzz

**Comment by brain-sick** [comment]
i was just creating my files half an hour ago, please consider this pull request

**Comment by Anupam-dagar** [comment]
@shivhek25 please provide link to your PR's :smile: I'll review

**Comment by AK-007** [comment]
@Anupam-dagar Plz review https://github.com/opencode18/CodeStash/pull/186

**Comment by Anupam-dagar** [comment]
i have asked @aswinzz to review it :smile:

**Comment by shivhek25** [comment]
@Anupam-dagar Please review https://github.com/opencode18/CodeStash/pull/190 and https://github.com/opencode18/OpenNews/pull/74
