### ISSUE TITLE
[URGENT] add this to your stories

### ISSUE THREAD

**Issue by Anupam-dagar** [opencode18/OpenCode-Collaborative#489]
It's the final day for OpenCode'18, we have all the goodies with us.Please use the below pic as your whatsapp, facebook, instagram stories to promote OpenCode'18.Let spread the word.
Let it stay for 24 hrs, 30 points for each platform.Post screenshot here.
Removal of the story after posting its screenshot here will result in a penalty.
Use the image provided below.In the caption you must atleast include #OpenCode18

![edited](https://user-images.githubusercontent.com/21174572/36060612-360d9c82-0e73-11e8-8f58-6636acee68e3.jpeg)

**Comment by yash-agarwal17** [comment]
#489 Added to story


![screenshot_2018-02-10-15-11-40-82](https://user-images.githubusercontent.com/34649409/36060715-ee276b62-0e74-11e8-86cd-c4b5a18637c5.png)

**Comment by AK-007** [comment]
![screenshot_2018-02-10-15-33-40-951_com whatsapp](https://user-images.githubusercontent.com/26346816/36060868-e275b168-0e77-11e8-9607-ee40a0432ebf.png)

**Comment by aadixiiita** [comment]
![screenshot_20180210-153358](https://user-images.githubusercontent.com/34688457/36060933-ccd2a964-0e78-11e8-9d4c-322535ec86df.png)

**Comment by Ace-Bansal** [comment]
Fb, insta and whatsapp 😛😛😛
![screenshot_2018-02-10-15-33-31-050_com instagram android](https://user-images.githubusercontent.com/34866483/36060942-ecbb2904-0e78-11e8-867f-a55e18710d6f.png)
![screenshot_2018-02-10-15-37-17-002_com facebook orca](https://user-images.githubusercontent.com/34866483/36060943-ed0a8a3a-0e78-11e8-84c4-cdd3483e00b6.png)
![screenshot_2018-02-10-15-29-25-595_com whatsapp](https://user-images.githubusercontent.com/34866483/36060944-ed5044d0-0e78-11e8-9d9c-6b1573b9be20.png)

**Comment by aadixiiita** [comment]
![screenshot_20180210-154414](https://user-images.githubusercontent.com/34688457/36060985-714e0f4c-0e79-11e8-9a5c-cb2a9de656aa.png)

**Comment by aadixiiita** [comment]
![screenshot_20180210-160215](https://user-images.githubusercontent.com/34688457/36061129-e306c578-0e7b-11e8-9a00-fc56d8636fea.png)

**Comment by falconis** [comment]
![screenshot_20180210-162053](https://user-images.githubusercontent.com/30634978/36061332-cfd69412-0e7e-11e8-9cbc-4790ed719ee1.png)
![screenshot_20180210-161930](https://user-images.githubusercontent.com/30634978/36061342-ee5f596e-0e7e-11e8-82b8-848b181b84ba.png)
![screenshot_20180210-161632](https://user-images.githubusercontent.com/30634978/36061348-fea2ef02-0e7e-11e8-9390-638383c43766.png)

**Comment by arpitmisraw** [comment]
![fbstory](https://user-images.githubusercontent.com/32339738/36061377-5b421c4c-0e7f-11e8-9a08-b7c51c4d2c19.png)
![instastory](https://user-images.githubusercontent.com/32339738/36061403-b20a81ae-0e7f-11e8-8ff6-1ccb03966580.png)
![whatsapp](https://user-images.githubusercontent.com/32339738/36061414-eaddfa88-0e7f-11e8-8a04-ee81e4aa0026.png)

**Comment by swaager** [comment]
![ee](https://user-images.githubusercontent.com/29673845/36061965-ebb7bd62-0e30-11e8-90d2-baffe944a38c.png)
![fb](https://user-images.githubusercontent.com/29673845/36062026-10b893f6-0e32-11e8-8c7b-2e4d4386ce73.png)
![ins](https://user-images.githubusercontent.com/29673845/36062123-dc2c18e0-0e33-11e8-944a-eed4c1e6af62.png)

**Comment by ananya-agrawal** [comment]
![screenshot_2018-02-10-18-02-29-451_com facebook katana](https://user-images.githubusercontent.com/33188930/36062171-b3f44b3c-0e8c-11e8-8f63-bb291f0fed9a.png)
![screenshot_2018-02-10-18-02-39-041_com whatsapp](https://user-images.githubusercontent.com/33188930/36062172-b4562dfc-0e8c-11e8-82b0-f1c3378c54b6.png)
![screenshot_2018-02-10-18-02-20-514_com instagram android](https://user-images.githubusercontent.com/33188930/36062173-b49f0a54-0e8c-11e8-8f3a-37b87c5496b7.png)

**Comment by aayushjoglekar** [comment]
![whatsapp image 2018-02-10 at 6 33 04 pm](https://user-images.githubusercontent.com/28949397/36062372-472529ea-0e91-11e8-9f44-c84317ce6092.jpeg)
![whatsapp image 2018-02-10 at 6 35 31 pm](https://user-images.githubusercontent.com/28949397/36062370-3e8c5ec0-0e91-11e8-9596-09e779ebf744.jpeg)

**Comment by shivhek25** [comment]
![whatsapp image 2018-02-10 at 6 46 58 pm-2](https://user-images.githubusercontent.com/24766191/36062449-e9e325e6-0e92-11e8-97fd-cf8471ee09e9.jpeg)
![whatsapp image 2018-02-10 at 6 46 58 pm](https://user-images.githubusercontent.com/24766191/36062450-ea1f97ce-0e92-11e8-96d6-ce0c5afc9420.jpeg)

**Comment by ashish4321** [comment]
![screenshot_20180210-215913](https://user-images.githubusercontent.com/25305613/36064275-9816a56e-0eae-11e8-99c0-00e0dcfe6dc5.png)
![screenshot_20180210-220124](https://user-images.githubusercontent.com/25305613/36064276-9a900cb8-0eae-11e8-9878-bfb4638916c6.png)
![screenshot_20180210-220329](https://user-images.githubusercontent.com/25305613/36064277-a1d2461c-0eae-11e8-9785-cd8366979750.png)

**Comment by Jigar3** [comment]
![screenshot_2018-02-10-17-41-20-021_com instagram android](https://user-images.githubusercontent.com/32068121/36064482-9710b88c-0eb1-11e8-81d5-4dd51cd29661.png)
![screenshot_2018-02-10-17-41-01-806_com whatsapp](https://user-images.githubusercontent.com/32068121/36064487-a8d88ca2-0eb1-11e8-9c59-c878e934b8f4.png)

![screenshot_2018-02-10-17-42-00-310_com facebook katana](https://user-images.githubusercontent.com/32068121/36064471-7bcd1c46-0eb1-11e8-9fa0-7510eafc6e0d.png)

**Comment by rahulkumaran** [comment]
Facebook, Insta, WhatsApp, Snapchat, Twitter and LinkedIn
![s4](https://user-images.githubusercontent.com/26206171/36064828-3b3c0704-0eb7-11e8-9de3-22b2005498bb.jpg)
![s3](https://user-images.githubusercontent.com/26206171/36064829-3b955aac-0eb7-11e8-8557-4ff4fcc198e9.jpg)
![s2](https://user-images.githubusercontent.com/26206171/36064831-3be34d34-0eb7-11e8-94e3-fcbdfdfe416c.jpg)
![s1](https://user-images.githubusercontent.com/26206171/36064832-3c92a702-0eb7-11e8-8ea8-20bf85f20caa.jpg)

![s6](https://user-images.githubusercontent.com/26206171/36064851-82b21498-0eb7-11e8-88f9-58795c58d5ad.jpg)
![a5](https://user-images.githubusercontent.com/26206171/36064852-82ef1154-0eb7-11e8-9db6-1dfc5c363270.jpg)

**Comment by ananya-agrawal** [comment]
![screenshot from 2018-02-10 23-31-26](https://user-images.githubusercontent.com/33188930/36065182-2da001f8-0ebd-11e8-954d-33438c2a5c50.png)
