### ISSUE TITLE
Fix loader

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#494]
the loader goes off before the site is fully loaded.Fix it

**Comment by aayushjoglekar** [comment]
I can do this. I have to just make a PR for another issue.

**Comment by aswinzz** [comment]
okay @aayushjoglekar  you can do it

**Comment by aayushjoglekar** [comment]
Please assign it to someone else @aswinzz I am fixing error in sorting of leaderboard scores.
