### ISSUE TITLE
The template of the page like this

### ISSUE THREAD

**Issue by goodday451999** [opencode18/OpenCode-Collaborative#7]
![screenshot 201](https://user-images.githubusercontent.com/33095476/34738093-fada0c9c-f59d-11e7-820a-d2a81d8dec2f.png)

**Comment by swaager** [comment]
I would like to work on this issue

**Comment by Anupam-dagar** [comment]
@aswinzz suggestions?

**Comment by aswinzz** [comment]
we cant change the template.use the current template!
