### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#72]
- comment before  solving issues. 
- solve merge conflicts. 
- follow proper code indentation. 
And other standard norms

**Comment by ananya-agrawal** [comment]
would like to solve this.

**Comment by brain-sick** [comment]
i would like to work on this

**Comment by gauthamzz** [comment]
assigned to @ananya-agrawal , since she commented first. 
also @brain-sick do only one issue at a time for now
